### ISSUE TITLE
jira issue view not showing comments

### ISSUE THREAD

**Issue by gennaro-tedesco** [ankitpokhrel/jira-cli#105]
Apologies for opening so many issues (I am just using the tool a lot!). I have noticed that `jira issue view <ticker-nr>` does not by default parse comments text. Is this intended behaviour or did I miss the documentation explaining how to visualise comments?

Likewise using `jira issue comment` lets you submit a comment but does not display the comments section either.

**Comment by ankitpokhrel** [comment]
Hi @gennaro-tedesco, this feature is on the to-do list and yet to be implemented. I will work on it as soon as I get some time.

Glad to know that the tool is helpful for you. Also, bug reports and PRs are welcome :)

**Comment by gennaro-tedesco** [comment]
Thank you, I did start having a look at the code and hopefully I will be able to help with it a little! :)

**Comment by bluejellybean** [comment]
I'm just starting to check out this codebase (and LOVING the entire project!), but my go skills are a bit lacking. Has there been any progress or movement on this card issue??
