### ISSUE TITLE
feature request: jira issue sprint

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#168]
> Please consider [opening a discussion](https://github.com/ankitpokhrel/jira-cli/discussions/categories/ideas) in `idea` category for the proposed feature if applicable. 

**Is your feature request related to a problem? Please describe.**
I have sprints. I have issues. I would like a way to associate the latter with the former.

**Describe the solution you'd like**
`jira issue sprint ISSUE-KEY SPRINT`

**Describe alternatives you've considered**
Using a web browser, but that sucks because Jira web pages suck.

**Additional context**
I don't know how common the "Sprint" attribute is for your "normal" Jira configurations, but my personal anecdata suggests that it's overwhelmingly popular.

**Comment by ankitpokhrel** [comment]
If I get it right, you want to assign sprint to an issue. It's something that is on my radar and hopefully will work on it soon. I am currently doing it from the UI as well.

**Comment by realtime-neil** [comment]
@ankitpokhrel yes, you understand perfectly. Thank you for taking the time to think about this; I do appreciate it.
