### ISSUE TITLE
Pick up the password/passkey from the .netrc file

### ISSUE THREAD

**Issue by cazador481** [ankitpokhrel/jira-cli#188]
Instead of having to put the passkey into an ENV variable, and store it in my dot files, can we pick also pick it up from the .netrc file?   I have a number of other tools that uses the .netrc file to store the jira keys and it would be a plus to have everything use the same location.

**Comment by ankitpokhrel** [comment]
Hi @cazador481, I don't use `.netrc` so the chances of me implementing this anytime soon are quite low. However, if someone can send a PR (and maintain this part of the feature), I would be happy to review and get it merged.

**Comment by ankitpokhrel** [comment]
This has been done in #329 and will be available in the next release. For now, you can either compile the [main branch manually](https://github.com/ankitpokhrel/jira-cli#development) or if you are using [Homebrew](https://brew.sh/) you can use `brew install jira-cli --HEAD`.
