### ISSUE TITLE
jira sprint list: `--plain` has no effect

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#207]
**Describe the bug**
`jira sprint list --plain` fails to display output in plain mode

**Please provide following details**
1. JiraCLI Version:
    ```
    $ go install github.com/ankitpokhrel/jira-cli/cmd/jira@9f5b0d005a2bf978d387245f03be560ca71b1154
    $ jira version
    (Version="", GitCommit="", GoVersion="go1.17.3", BuildDate="", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.6 LTS
    Release:	18.04
    Codename:	bionic
    ```
4. What terminal are you using? Also mention version.
    ```
    # GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2
    ```

**To Reproduce**

```
$ nohup jira sprint list --plain >jira-sprint-list.txt &
[1] 10801
nohup: ignoring input and redirecting stderr to stdout

$ ls jira-sprint-list.txt 
jira-sprint-list.txt
[1]+  Stopped                 nohup jira sprint list --plain > jira-sprint-list.txt

$ awk 1 jira-sprint-list.txt 
⠴ Fetching sprints... 
```

**Expected behavior**
`jira sprint list --plain` prints the list of sprints to standard output.

**Screenshots**
not applicable

**Additional context**
none

**Comment by ankitpokhrel** [comment]
@realtime-neil  `jira sprint list` loads preview ui by default and this section is not designed to handle `--plain` output.

If you wish to get a list of sprints in a non tty mode then you will explicitly need to load this list in `table` ui and use the plain option. For example, the command below should work.

```sh
jira sprint list --table --plain
```

If you wish to load issues in a sprint in plain mode, you can do the following.

```sh
jira sprint list SPRINT_ID --plain
```

**Comment by realtime-neil** [comment]
@ankitpokhrel whoops, I must missed the `--table` option in the `--help` message. Sorry about that.

Still, though, if this isn't a bug, then it's at least an annoyance. If the user doesn't remember to pass the `--table` option, then `jira` assumes that the `tty` exists --- even when the `tty` clearly _doesn't_ exist. In that regard, this issue is similar to #187.

**Comment by ankitpokhrel** [comment]
I agree that it's a bit of an annoyance. I will see how I can improve that part.

I will close this issue for now since we already have #187 open.
