### ISSUE TITLE
jira issue list: 400 Bad Request

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#210]
**Describe the bug**
```
$ jira issue list
⠦ Fetching issues... 
Error:
  - The value '' does not exist for the field 'project'.

jira: Received unexpected response '400 Bad Request'.
Please check the parameters you supplied and try again.
```

**Please provide following details**
1. JiraCLI Version:
    ```
    $ go install github.com/ankitpokhrel/jira-cli/cmd/jira@v0.2.0
    $ jira version 
    (Version="dev", GitCommit="", GoVersion="go1.17.3", BuildDate="", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Ubuntu 18.04
    ```
4. What terminal are you using? Also mention version.
    ```
    $ gnome-terminal --version
    # GNOME Terminal 3.28.2 using VTE 0.52.2 +GNUTLS -PCRE2
    ```

**To Reproduce**

```
$ go install github.com/ankitpokhrel/jira-cli/cmd/jira@v0.2.0 && jira issue list
⠼ Fetching issues... 
Error:
  - The value '' does not exist for the field 'project'.

jira: Received unexpected response '400 Bad Request'.
Please check the parameters you supplied and try again.
```

**Expected behavior**
See the list of issues.

**Screenshots**
Not applicable.

**Additional context**
Not applicable.

**Comment by ankitpokhrel** [comment]
@realtime-neil v0.2.0 has some BC incompatible change in the config so you need to re-generate the config as mentioned in [the changelog](https://github.com/ankitpokhrel/jira-cli/releases/tag/v0.2.0).

You can use `jira init` to re-generate the config.

**Comment by realtime-neil** [comment]
That fixed it. What kind of configuration upgrading strategy do you have? As a minor bump (from `0.1.*` to `0.2.*`), my `0.1.*` configuration should have been supported.

**Comment by ankitpokhrel** [comment]
Its usually [semver](https://semver.org/), `x.y.z`. Since the tool is not yet considered complete, there might be a breaking change for each bump in `y` until it reaches `1.*`.

> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by realtime-neil** [comment]
@ankitpokhrel point taken. I'll wait until you hit 1.0.0 before I start bothering you about breaking changes in the config file format. :smile:
