### ISSUE TITLE
Possibility to use username/password as ENV variables instead of JIRA_API_TOKEN

### ISSUE THREAD

**Issue by amgohan** [ankitpokhrel/jira-cli#214]
> Please consider [opening a discussion](https://github.com/ankitpokhrel/jira-cli/discussions/categories/ideas) in `ideas` category if applicable. Your feature will be prioritized on based on the number of votes.  

**Is your feature request related to a problem? Please describe.**
I can't use the jira-cli, I have only a username/password and can't generate an API token myself.

**Describe the solution you'd like**
The possibility to support a JIRA_USERNAME/JIRA_PASSWORD as ENV variables instead of JIRA_API_TOKEN

**Comment by ankitpokhrel** [comment]
@amgohan if you are using on-premise installation, you can add password in `JIRA_API_TOKEN` env and use the username when initializing the config with `jira init`. For cloud installation, the recommended way is to use the API token.

**Comment by amgohan** [comment]
thanks it works.
