### ISSUE TITLE
Unable to generate configuration when jira init.

### ISSUE THREAD

**Issue by abbi1229** [ankitpokhrel/jira-cli#215]
1. Version:
    ```
    JiraCLI (Version="dev", GitCommit="", GoVersion="go1.17.3", BuildDate="", Compiler="gc", Platform="linux/amd64")
    Atlassian Jira (v8.13.11), on-premise.
    CentOS Linux release 7.8.2003 (Core) , Konsole 2.10.5
    ```
2. Steps
    ```
     ~/go/bin> jira init
     ? Installation type: Local
     ? Link to Jira server: https://myjira.com/
     ? Login username: larry
     ? Default project: PK
     � Fetching boards for project 'PK'... 
     � Unable to generate configuration: please provide options to select from
    ```
3. Debug
    ```
    go/bin> curl --request GET \
        --url 'https://myjira.com/rest/agile/1.0/board?projectKey=PK' \
        --user "larry:***"
    ```
    Jira server return:
    ```
    {"maxResults":50,"startAt":0,"total":0,"isLast":true,"values":[]}
    ```
The message returned by the jira server is expected?
Or is there any suggested way to solve it?
Thanks!

**Comment by ankitpokhrel** [comment]
Hi @abbi1229, it looks like you don't have any `board` in a project. Is it so?

**Comment by abbi1229** [comment]
Hi @ankitpokhrel 
No, We don't have any ``Board`` in a project.
I tried to create a ``Board`` but I don’t have permission.  😭
Our team is used to using ``DashBoard`` or just open ``Project`` then filter the issue.
Is it possible that jira-cli works without a ``Board`` ?

**Comment by abbi1229** [comment]
Hi @ankitpokhrel,
Our project was created with ``Bug tracking`` of project template. 
https://www.atlassian.com/software/jira/features/bug-tracking
Not a ``Kanban`` or ``Scrum``.
So there will not have a ``Board`` in default.
Could jira-cli support this type of project template?

**Comment by ankitpokhrel** [comment]
@abbi1229 You can now select `None` for empty boards and rest of the things should just work.

<img width="241" alt="Screen Shot 2021-12-02 at 7 22 01 PM" src="https://user-images.githubusercontent.com/2364546/144480692-33c1f04d-c837-4026-94ba-c28aef1a0a49.png">

The change will be available in the next release.

For now, if you wish to use this feature, you can either [compile from source](https://github.com/ankitpokhrel/jira-cli#development) or if you are using homebrew you can build binary from `HEAD` (requires `make`, `git` and `go`)

```sh
brew uninstall jira-cli
brew install jira-cli --HEAD
```
