### ISSUE TITLE
jira epic list --plain

### ISSUE THREAD

**Issue by gennaro-tedesco** [ankitpokhrel/jira-cli#223]
**Describe the bug**

```
jira epic list --plain | grep <something>
``` 
hangs indefinitely.

**Please provide following details**
1. JiraCLI Version:

    ```
    jira version
    (Version="", GitCommit="", GoVersion="go1.16.2", BuildDate="", Compiler="gc", Platform="darwin/amd64")
    ```

3. What operating system are you using? Also mention version.
    ```
    macOS 12.0.1 Monterey
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm2 (Version 3.4.12)
    ```

**To Reproduce**

1. `jira epic list`
2. pipe the above into grep
3. See error

**Expected behavior**
Is `jira epic list` working with `--plain`? What I want to achieve is to be able to filter by epic titles when I do not remember the epic key number. Moreover, given the current state, would it not be possible instead to show a dynamic list of epics that can be filtered agains (like in case of users or metadata flags for issues)?

**Comment by ankitpokhrel** [comment]
@gennaro-tedesco `jira epic list` loads preview ui by default and this section is not designed to handle `--plain` output.

If you wish to get a list of epics in a non tty mode then you will explicitly need to load this list in `table` ui and use the plain option. For example, the command below should work.

```sh
jira epic list --table --plain
```

If you wish to load issues in an epic in plain mode, you can do the following.

```sh
jira epic list EPIC-KEY --plain
```

Same goes for `sprints`. I understand that this is bit confusing and I am looking for a way to improve this. Let me know if you have any better idea.

Another option to get list of `epics` is to use issue filter.

```sh
jira issue list -tEpic
```

And use `--plain` to get plain output

```sh
jira issue list -tEpic --plain
```

**Comment by gennaro-tedesco** [comment]
Thank you very much `jira epic list --table --plain` works just fine and I am going to use this one to grep for titles.

However, strangely enough
```
jira epic list EPIC-KEY --plain
```
returns the error (after I specify my EPIC-KEY)
```
Error:
  - The request contains a next-gen issue. This operation cant add next-gen issues to epics. To add a next-gen issue to an epic, use the Edit issue operation and set the parent property (i.e., `"parent":{"key":"PROJ-123"}` where `PROJ-123` has an issue type at level one of the issue type hierarchy). See <a href="https://developer.atlassian.com/cloud/jira/platform/rest/v2/"> developer.atlassian.com </a> for more details.

jira: Received unexpected response '400 Bad Request'.
Please check the parameters you supplied and try again.
```
Interestingly, this is the same error that I am now getting when I want to add issues to the epics (using `jira epic add`): probably the jira API that you are calling changed their specific for "new generation" projects and the return values cannot be parsed as before anymore (just a wild guess, I remember seeing similar errors in the JIRA ui for some new generation projects).

*Idea* 

> I understand that this is bit confusing and I am looking for a way to improve this. Let me know if you have any better idea.
 
The way I usually deal with these situations in my workflow is by building myself custom cheatsheets of this or that other programme: in my case I use [navi](https://github.com/denisidoro/navi) but there is many more. For instance I now have a `jira.cheat` on my computer that contains all these one-liners that I can access via key-binding, so I need not ever remember how to do anything, I just need to write it down once (which is also the reason why I am often around the issues here asking what flag or what options I must use, because I am building all these little functions for myself). Ideally at some point we can publish a collection of `jira.cheat` so that users need not even learn anything about your application, they already have most commands at their disposal (obviously the commands will be different according to the cheatsheets they use, but you get my point).

In the past I tried to contribute to `navi` with cheatsheets for other applications but the process seems quite slow (PR are not looked at regularly), so one possible solution is to create some sort of `CONTRIBUTE.md` or `cheatsheet` folder/branch in this project so that users can just go there and clone the commands they need :)

**Comment by ankitpokhrel** [comment]
@gennaro-tedesco The way epics are handled is changed in `next-gen` project and is not backwards compatible with `classic` projects. The support for `next-gen` project was added in [v0.2.0](https://github.com/ankitpokhrel/jira-cli/releases/tag/v0.2.0). It looks like you've compiled the tool from source so I cannot tell if you are using latest build or the old one. Please try with the latest source and it should work just fine. Note that you will need to regenerate config after update.

Thank you for sharing the idea. I do have a plan to create aliases and probably also add it to [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins) since I rely on it for other shortcuts. Adding a cheatsheet shoulds like a good idea but I will wait until things are stable. Please feel free to share the cheatsheet you have created, it will help me learn how the tool is being used and take a better decision for new features.

**Comment by gennaro-tedesco** [comment]
I have re-installed via `brew install jira-cli --HEAD`, I will try to compile from source to get the latest and report back on whether it works.

Likewise, if I get most shortcuts and functions working for the boards, issues and epics I will share the cheatsheet I am using so that you can have a look.

**Comment by gennaro-tedesco** [comment]
Explicitly installing v0.2.0 solved the problem and now I can correctly visualise new generation projects (likewise after re-generating the config file I can correctly query everything). For completeness I am now on 
```jira version
(Version="0.2.0", GitCommit="06888ef8934a2b95d4a729cc024f11e485239a36", GoVersion="go1.17.2", BuildDate="2021-11-20", Compiler="gc", Platform="darwin/amd64")```

We can close this issue as all is well with the epics (using `--table` will do). Now that I clean up some functions and commands I will share it so that we can have a look together (meanwhile maybe we can think of the best way to share it).
