### ISSUE TITLE
JSON Output

### ISSUE THREAD

**Issue by tstrijdhorst** [ankitpokhrel/jira-cli#228]
Really glad I found this project! Allows me to do many things very quickly.

I am creating a small CLI app that uses this app to automate some parts of my flow and it would really help if there was an option to display the output in json format. Now I am parsing the `--plain` which works but doesn't feel the most stable.

**Comment by ankitpokhrel** [comment]
@tstrijdhorst this CLI tool is created for a different purpose and adding json output would just complicate things. If you want a json output you can use tools like [httpie](https://github.com/httpie/httpie) or [curl](https://github.com/curl/curl) to call [the API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/) directly for a json response.

```sh
http GET https://<server>/rest/api/2/issue/ISSUE-1 --auth "<user>:${JIRA_API_TOKEN}"
```

**Comment by mavaddat** [comment]
I agree that parseable output would be a nice feature. Plain text is surprisingly difficult to parse.

**Comment by ryuheechul** [comment]
as suggested above calling via API directly was a good fallback to access data as `json` format 👍🏼 and `--debug --plain` with `jira` is helpful to reuse request bodies of what `jira` CLI uses instead of having to "reinvent" the request.

**Comment by nhed** [comment]
If the project readme states that this tool is inspired by the Github CLI one should note that commands there can take the `--json` & `--jq` flags  allowing users to build automation ontop of that tool.

Sure we can read the API docs but harnessing an existing tool helps alot

**Comment by erawhctim** [comment]
I'll add that supporting `jq` and/or raw JSON output would help unlock new features for users that aren't yet officially added as CLI arguments/functions. It would be extremely valuable.

If the Jira API returns some field in its response that the CLI hasn't yet built support to output/surface to users, parsing the raw output via `jq` could un-block those users and make the CLI more extensible!
