### ISSUE TITLE
JIRA_API_TOKEN and Authorization: Bearer

### ISSUE THREAD

**Issue by pstryk** [ankitpokhrel/jira-cli#229]
Hi,
my curl works ok with **Authorization: Bearer** header. Example:
`curl -X GET -H "Authorization: Bearer xxx" \  
-H "Content-Type: application/json" \
"https://jira.url.com/rest/api/2/user/properties?username=some_user"`

But when I do **jira init** I get 401.

My JIRA_API_TOKEN is stored in .zshrc with:
`export JIRA_API_TOKEN=xxx`

**Comment by heiba** [comment]
Same here, I'm getting the same issue

**Comment by heiba** [comment]
Adding export JIRA_API_TOKEN=xxx fixed it for me 
https://github.com/ankitpokhrel/jira-cli/issues/133#issuecomment-977839749

**Comment by 1enny** [comment]
Your example works because you use `Authorization: Bearer `
Looks like `jira-cli` currently uses `Authorization: Basic `  https://github.com/ankitpokhrel/jira-cli/blob/e229260dcdf04b855555feac7ba063bac3795257/pkg/jira/client.go#L225

**Comment by ankitpokhrel** [comment]
Yes, the tool is using a basic auth as @1enny pointed out. But, as long as `JIRA_API_TOKEN` is available in the shell, I think it should not be a problem.

@pstryk do you get a valid response if you pass `--user` option instead of a `Bearer` token like in the example below?

```sh
curl --request GET \
  --url 'https://<your-server-host>/rest/api/3/myself' \
  --user "<your-email>:$JIRA_API_TOKEN"
```

**Comment by pstryk** [comment]
I got it working with 
`--user login:$JIRA_PASSWORD_AS_API_TOKEN`

Case can be closed.

**Comment by wolfiesites** [comment]
hmm.. I m on Kubuntu 21.10 x86_64 
This command works for me:
```
curl --request GET \
  --url 'https://<your-server-host>/rest/api/3/myself' \
  --user "<your-email>:$JIRA_API_TOKEN"
```
It returns json.

However `jira init` fails with error:
Received unexpected response '401 Unauthorized' from jira. Please try again.
:sad_peppe:

I installed `jira-cli` package via brew for linux.

**Comment by wolfiesites** [comment]
Oh ok GOT it!!! 

For those struggling 
in `.bashrc`
`export JIRA_API_TOKEN="XXXXXX`

word `export` is needed which I ealier forgotten.

**Comment by hu13** [comment]
I still have this issue with jira-cli:
```
(Version="1.0.0", GitCommit="e94433858ee31e16d4b41c14032864f3c5361115", CommitDate="2022-06-23T06:35:37+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="darwin/arm64")
```
I did the export correctly and curl works.

**Comment by hu13** [comment]
are there log files or verbose mode for jira-cli that we can check for more details?
