### ISSUE TITLE
fix usage: jira issue comment add

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#230]
**Describe the bug**
The `COMMENT_BODY` is documented as a mandatory positional argument even though it's not.

**Please provide following details**
1. JiraCLI Version:
```
$ go install github.com/ankitpokhrel/jira-cli/cmd/jira@e229260dcdf04b855555feac7ba063bac3795257 && jira version
(Version="dev", GitCommit="", GoVersion="go1.17.5", BuildDate="", Compiler="gc", Platform="linux/amd64")
```

2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
```
cloud
```

3. What operating system are you using? Also mention version.
```
$ cat -n /etc/os-release 
     1	NAME="Ubuntu"
     2	VERSION="20.04.3 LTS (Focal Fossa)"
     3	ID=ubuntu
     4	ID_LIKE=debian
     5	PRETTY_NAME="Ubuntu 20.04.3 LTS"
     6	VERSION_ID="20.04"
     7	HOME_URL="https://www.ubuntu.com/"
     8	SUPPORT_URL="https://help.ubuntu.com/"
     9	BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    10	PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    11	VERSION_CODENAME=focal
    12	UBUNTU_CODENAME=focal
```

4. What terminal are you using? Also mention version.
```
$ gnome-terminal --version 
# GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
```

**To Reproduce**

```
$ jira issue comment add FOOBAR-42 --no-input --template - <<'EOF'
This is a comment.
EOF
```

**Expected behavior**
If the `COMMENT_BODY` were really necessary, then one might expect to see an error message like this:
```
Error:
  - comment: Comment body can not be empty!
```
Since `COMMENT_BODY` is not actually necessary, the `jira issue comment add --help` message should be changed from this...
```
$ jira issue comment add --help | head -n4
Add adds comment to an issue.

USAGE
  jira issue comment add ISSUE-KEY COMMENT_BODY [flags]
```
...to this:
```
$ jira issue comment add --help | head -n4
Add adds comment to an issue.

USAGE
  jira issue comment add ISSUE-KEY [COMMENT_BODY] [flags]
```

**Screenshots**
not applicable

**Additional context**
not applicable

**Comment by realtime-neil** [comment]
Addendum:

`jira issue comment add` tolerates the following undocumented orderings of options and positional arguments:

```
jira issue comment add FOOBAR-42 --no-input "comment body"
jira issue comment add --no-input FOOBAR-42 "comment body"
```

The usage should be changed to reflect these supported orderings or the implementation should be changed to reject them.

**Comment by ankitpokhrel** [comment]
> Steps to reproduce the behavior:

> ```
> $ jira issue comment add FOOBAR-42 --no-input --template - <<'EOF'
> This is a comment.
> EOF
> ```

@realtime-neil you are still passing `COMMENT_BODY` here as a template. Jira API doesn't allow you to add a comment without body (it won't make any sense to add a comment without body right?). The [README](https://github.com/ankitpokhrel/jira-cli#add) mentions few different ways to get comment body for the command.

```sh
# Normal usage
$ jira issue comment add ISSUE-1 "My comment body"

# Load comment body from a template file
$ jira issue comment add ISSUE-1 --template /path/to/template.tmpl

# Get comment body from standard input
$ jira issue comment add ISSUE-1 --template -

# Or, use pipe to read input directly from standard input
$ echo "Comment from stdin" | jira issue comment add ISSUE-1
```

Regarding your query about undocumented orderings, the flags are [POSIX-complaint](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) and AFAIK the flag could be in any order. From the docs:
> Options may be supplied in any order, or appear multiple times. The interpretation is left up to the particular application program. 

I don't think this is a problem here. If it is helpful we can add more example in command help `jira issue comment add -h`.

**Comment by realtime-neil** [comment]
@ankitpokhrel 

> The README mentions few different ways to get comment body for the command.

Yes, the README does mention the various ways to effect an issue comment. The `jira issue comment add` usage does not. In conventional usage verbiage

```
my-tool [OPTION]... ARGUMENT
```

connotes a command that takes some arbitrary options (or none at all) and exactly one positional argument, customarily given after all (any) `OPTARG`s. Compare/contrast this with

```
my-tool [OPTION]... [ARGUMENT]
```

which connotes exactly one _optional_ positional argument. It would be nice if this were enforced by the implementation of `jira issue comment add`. Failing that, it should at least be mentioned in the command usage, if only to avoid surprising the user.

While we're on the subject of user surprises, consider the following:

```
ira issue comment add FOOBAR-42 "comment body positional" --template - <<'EOF'
> comment body template
```

In this example, the "comment body positional" wins over "comment body template". This should probably be documented in the usage, as well.

**Comment by realtime-neil** [comment]
@ankitpokhrel 

> the flags are POSIX-complaint and AFAIK the flag could be in any order

This remark deserves some qualification. The presentation and ordering of the `OPTARG`s and positional arguments can be arbitrary, but only after the complete sub-sub-sub-command. That is,

```
jira issue comment add --no-input FOOBAR-42 'hello comment!'
```

is valid, but

```
jira issue comment --no-input add FOOBAR-42 'hello comment!'
```

is not --- even though `add` is the only sub-sub-sub-command under the `jira issue comment` sub-sub-command.

**Comment by ankitpokhrel** [comment]
@realtime-neil I updated the docs to reflect our discussion in #235. I hope that's clear enough 🙃

**Comment by realtime-neil** [comment]
@ankitpokhrel we never had any discussion in #235 . This is unclear and I'm confused.

I'm happy to see that you're maintaining the documentation, but this issue wasn't about documenting anything. It was (and is) about changing the `jira issue comment add` usage (and/or implementation) such that the `--help` message more accurately shows how to invoke the (sub-sub-sub-) command and how arguments thereto are parsed.

**Comment by ankitpokhrel** [comment]
@realtime-neil I just re-read entire thread and realized that `COMMENT_BODY` is not optional in help 🤦🏻. Sorry for the confusion.

```
jira issue comment add ISSUE-KEY [COMMENT_BODY] [flags]
```

And since this is a really small change, a PR would've been nice :)

**Comment by realtime-neil** [comment]
> And since this is a really small change, a PR would've been nice :)

I'm happy to oblige. :grin:
