### ISSUE TITLE
--plain not working as expected

### ISSUE THREAD

**Issue by kharthigeyan** [ankitpokhrel/jira-cli#233]
**Describe the bug**
Command: `jira issue list -a$(jira me) --plain`
The following text is offsetting the text output.
"⠧ Fetching issues..."

**Please provide following details**
1. JiraCLI Version:

```
(Version="0.2.0", GitCommit="06888ef8934a2b95d4a729cc024f11e485239a36", GoVersion="go1.17.2", BuildDate="2021-11-20", Compiler="gc", Platform="darwin/amd64")
```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
```
Jira cloud
```
3. What operating system are you using? Also mention version.
```
macOS Catalina 10.15.7
```
4. What terminal are you using? Also mention version.
```
iTerm 2 Build 3.4.3
```

**To Reproduce**

1. Run this command: "jira issue list -a$(jira me) --plain"
2. Check the first line of the output.
3. If you see this text "⠧ Fetching issues...", then it is a problem.

**Expected behavior**
We should not see this text in the first line "⠧ Fetching issues..." for at least --plain option.

**Screenshots**
![image](https://user-images.githubusercontent.com/8716763/146827163-5d749772-f5b8-4dbb-a7af-1aed0a2e107b.png)

**Additional context**

**Comment by ankitpokhrel** [comment]
Hi @kharthigeyan, you can redirect `stderr` to `/dev/null` 

```sh
jira issue list -a$(jira me) --plain 2>/dev/null
```

**Comment by realtime-neil** [comment]
@ankitpokhrel wouldn't a better solution be to clear the terminal device backing `stderr` once you're done writing status messages to it?
