### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#243]
The benefits associated with reproducible builds (and the costs associated with non-reproducible builds) are better explained here:
https://reproducible-builds.org/

tldr; reproducible builds are good and jira-cli would be improved by having reproducible builds.

**Comment by ankitpokhrel** [comment]
@realtime-neil if you install the binary using `go install`, generated `SourceDate` will be gibberish (example below). It would be nice if we can inject the current date to get an idea of when the build was created. A fair share of users relies on `go install` to install the tool.

```
(Version="dev", GitCommit="ffffffffffffffffffffffffffffffffffffffff", SourceDate="1969-12-31T23:59:59+00:00", GoVersion="go1.16.12", Compiler="gc", Platform="linux/arm64")
```

**To reproduce:**
```
go install github.com/ankitpokhrel/jira-cli/cmd/jira@main
```

What I would propose is:
- Add a `BuildDate` which is a date when the build was created. This will be a date of release for pre-built binaries or current datetime when using `go install` or `brew install jira-cli --HEAD`.
- Rename `SourceDate` to `CommitDate`. Commit date sounds a bit clear to me.
- Leave `GitCommit` and `CommitDate` empty if we cannot fetch those info for manual installs. On the other hand we will always have a valid value for `BuildDate`.

Example of how it will look for `go install`.
```
(Version="dev", GitCommit="", CommitDate="", BuildDate="2022-01-03T22:25:40+00:00", GoVersion="go1.16.12", Compiler="gc", Platform="linux/arm64")
```

Let me know you thoughts.

**Comment by realtime-neil** [comment]
> Add a BuildDate which is a date when the build was created. This will be a date of release for pre-built binaries or current datetime when using go install or brew install jira-cli --HEAD.

How do you populate `BuildDate` with `go install` without overriding the `GOFLAGS`?

**Comment by ankitpokhrel** [comment]
Using current date as default `BuildDate` in `version.go` should do the trick?

**Comment by realtime-neil** [comment]
@ankitpokhrel do I understand correctly that you want a string literal of the form
```
2022-01-04T14:25:10+00:00
```
as the "default" value for the `BuildDate` ? And that this value should be changed by a human developer within the content of `internal/version/version.go` immediately prior to a release?

If I understand correctly, then that's easy enough to implement. The hard part is that this creates a "busy work" chore for you to do on every release; i.e., updating the `BuildDate` each time.

**Comment by realtime-neil** [comment]
@ankitpokhrel also, with this scheme, assuming that a human never assigns a `BuildDate` in the future, this means that the `CommitDate` will always _follow_ the `BuildDate` --- because committing the change must follow the creation of the change.

**Comment by ankitpokhrel** [comment]
What I meant was, we can construct `BuildDate` in a similar way like we are setting value for `SourceDate`.

![Screen Shot 2022-01-04 at 9 02 59 PM](https://user-images.githubusercontent.com/2364546/148116978-563dac13-c57e-4357-ab2d-f3e09fc381e9.png)

In `Makefile` we can pass build date as such:

```sh
BUILD_DATE = $(shell TZ=UTC date +%Y-%m-%dT%T\Z)
```

And in `.goreleaser.yml` we can do:

```yml
- -X github.com/ankitpokhrel/jira-cli/internal/version.BuildDate={{.Date}}
```

If any build system like `go install` doesn't pass `BuildDate` we will always have current datetime as a default value.

**Comment by realtime-neil** [comment]
@ankitpokhrel what you have described is the antithesis of a reproducible build. Even if you were able to "bake in" the value of the `BuildDate` variable at build time, it would be different for every invocation of `go install ./...` and/or `make install` (ignoring object caching).

To have a reproducible build, you need a one-to-one mapping of source code to built artifact. Values injected from the environment that depend on time violate this principle.

**Comment by realtime-neil** [comment]
Also, the concept of a build date is useless for an artifact that has a reproducible build. A given commit always produces the same artifact, so there's no point in tracking when it was produced.

**Comment by ankitpokhrel** [comment]
I think we might be talking about different things here. The idea of reproducible build is one thing and figuring out the closest build when someone reports the issue in the tool is another.

When someone who installed an app using `go install` creates an issue, the current version output doesn't give the slightest idea of what the user has installed.

```
(Version="dev", GitCommit="ffffffffffffffffffffffffffffffffffffffff", SourceDate="1969-12-31T23:59:59+00:00", GoVersion="go1.16.12", Compiler="gc", Platform="linux/arm64")
```

The idea behind build date is just to get a sense of what the user _might_ have possibly installed. It won't be accurate but doesn't hurt to have one IMO. Or, perhaps you have a better idea?

**Comment by realtime-neil** [comment]
Okay, you're trying to solve the problem where both the `GitCommit` and the `SourceDate` are either unknown or ignored. Okay, yes, agreed, if you want to report a BuildDate in that case, then I can absolutely implement it.

**Comment by realtime-neil** [comment]
Is this what you want? https://github.com/ankitpokhrel/jira-cli/pull/245

It looks weird to me, but it does seem to fulfill your requirements.

**Comment by realtime-neil** [comment]
@ankitpokhrel here it is in action:

```
$ go install ./... && jira version && sleep 1 && jira version
(Version="dev", GitCommit="", CommitDate="", BuildDate="2022-01-04T23:34:12+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="linux/amd64")
(Version="dev", GitCommit="", CommitDate="", BuildDate="2022-01-04T23:34:13+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="linux/amd64")
```

**Comment by realtime-neil** [comment]
@ankitpokhrel 

> The idea behind build date is just to get a sense of what the user might have possibly installed.

If you want `go build` and/or `go install` to produce a program with embedded version information, then you need to add that information to source control. For a golang project, this could be implemented as
```
const (
    Version = "0.1.2"
)
```
or
```
//go:embed version.txt
var Version string
```

This, of course, means that a human needs to bump the version for every release.
