### ISSUE TITLE
Create issue with current sprint

### ISSUE THREAD

**Issue by theapache64** [ankitpokhrel/jira-cli#246]
Is this possible with a single command ?

**Comment by ankitpokhrel** [comment]
@theapache64 Unfortunately not. I don't think Jira allow it in a single API call since sprint is a custom field and not valid for all boards. So, even if we add the functionality to the tool we will still have to use 2 API call internally.

**Comment by theapache64** [comment]
@ankitpokhrel Alright. No problem. I can write a bash function. Thanks for making this amazing tool 👍

**Comment by naveg** [comment]
+1 for this feature. It would be great if you could do `jira sprint add --current ISSUE_ID`

**Comment by jktzes** [comment]
> +1 for this feature. It would be great if you could do `jira sprint add --current ISSUE_ID`

Or you can just run `issue=$(jira issue create -tTask -s"your summary" -b"your description" --no-input | tail -1 | rev | cut -c 1-4 | rev) && jira sprint list | grep --line-buffered -e 'active' | grep -e 'extra filter words if needed' | cut -c 1-4 | xargs -I{} jira sprint add {} $issue` If your sprint ID is 4 digits and ticket number is 4 digits.

**Comment by silouanwright** [comment]
Doesn't this documentation explain that you can add custom fields to tickets upon creation? https://github.com/ankitpokhrel/jira-cli/discussions/346
