### ISSUE TITLE
Support password manager for API token

### ISSUE THREAD

**Issue by d-miketa** [ankitpokhrel/jira-cli#247]
I'd rather not store my Jira API token in plain text. Would it be possible to add support for standard keyrings and password managers? Many thanks!

**Comment by bspinner** [comment]
+1, I'd like to see interaction with the macOS keychain.

Storing tokens in plaintext in my env is a no-go for me :(

@ankitpokthrel What would be the TODOs for this?

**Comment by ankitpokhrel** [comment]
@bspinner Keychain support is something in my TODO list. I can't give a date, but this will hopefully be done soon. There are other priorities at the moment.

If someone wants to contribute, we can utilize [this lib](https://github.com/zalando/go-keyring) to interact with keychain.

**Comment by ankitpokhrel** [comment]
This is done with #348 and will be available in the next release. You can add a password item in your keychain with item name as `jira-cli` and account name as your login email/username. The order in which the tool look for a token is `env -> .netrc -> keychain`.

Please feel free to comment or open a new issue if this doesn't work for you.
