### ISSUE TITLE
Change default browser

### ISSUE THREAD

**Issue by ankitpokhrel** [ankitpokhrel/jira-cli#250]
### Discussed in https://github.com/ankitpokhrel/jira-cli/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **klammbueddel** January  6, 2022</sup>
Great tool, just just stumbled across it and fell in love. 

I am using it in WSL. I tried a lot to change the default browser (update-alternatives --config x-www-browser, setting BROWSER variable), but still Google Chrome within WSL is started. I'd like to open issues in Firefox of my host which works fine with wslview. 

How can I tell jira-cli to use wslview as default browser?

Thank you for this awesome tool!</div>

**Comment by klammbueddel** [comment]
Thank you so much for your effort! Enjoy your coffee ;)

**Comment by ankitpokhrel** [comment]
@klammbueddel could you please try with the build from `fix-issue-250` branch and let me know how it goes?

You can either [compile source](https://github.com/ankitpokhrel/jira-cli#development) from the branch or use `go install github.com/ankitpokhrel/jira-cli/cmd/jira@fix-issue-250` to build binary directly from the branch (requires `make`, `git` and `go1.16+`)

**Comment by klammbueddel** [comment]
Works like a charme 👍
Thank you so much!

**Comment by QuAzI** [comment]
Works fine to set "Working profile" for FF instead of default
```powershell
$env:JIRA_BROWSER="'c:\Program Files\Mozilla Firefox\firefox.exe' -p dev"
```

But is there any way to move this setting to $HOME/.config/.jira/.config.yml ?
To not spam into env
