### ISSUE TITLE
✗ Unable to generate configuration: Config File "config" Not Found in "[]"

### ISSUE THREAD

**Issue by dep** [ankitpokhrel/jira-cli#255]
**Describe the bug**
After running `jira init` i receive the following error

```
▶ jira init
? Installation type: Cloud
? Link to Jira server: https://invoca.atlassian.net
? Login email: dpeck@invoca.com
? Default project: TECH
? Default board: Engineering Backlog Scrumban Board
⠋ Creating new configuration...
✗ Unable to generate configuration: Config File "config" Not Found in "[]"
```

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="darwin/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    MacOs 10.15.7
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm2 Build 3.4.12
    ```

**To Reproduce**

1. install as documented
2. run jira init
3. See error

**Expected behavior**
no errors

**Comment by dep** [comment]
Closing as this worked after using the `Local` configuration option (apologies, misread the instructions).

**Comment by stobias123** [comment]
FWIW I just ran into this issue if I had a trailing slash in jira server url

**Comment by ccmattr** [comment]
Trailing slash was also my issue then I hit this error
