### ISSUE TITLE
Help text for sprint list defines a static acceptable list of columns that's incorrect

### ISSUE THREAD

**Issue by ccmattr** [ankitpokhrel/jira-cli#263]
**Describe the bug**

The help text says the following:
![image](https://user-images.githubusercontent.com/83646278/149322004-f9ac4546-ec05-42a3-b2b3-7e20441c6c7c.png)

However the names aren't accureate to the header names in the output which can be used as valid.
```
jira sprint list 99 -p DEVOPS --plain --columns TYPE,KEY,STATUS
```
![image](https://user-images.githubusercontent.com/83646278/149322234-55163a05-edbe-408a-a42f-bb7755d43826.png)
 

**Please provide following details**
1. JiraCLI Version:
    ```
   (Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Ubuntu 20.04.2 LTS running in WSL2 on Windows 11 Pro version 10.0.22000
    ```
4. What terminal are you using? Also mention version.
    ```
    Windows terminal Version 1.11.3471.0
    ```

**Comment by ankitpokhrel** [comment]
Fixed in #320
