### ISSUE TITLE
Doesn't honor default browser

### ISSUE THREAD

**Issue by jaymzh** [ankitpokhrel/jira-cli#266]
**Describe the bug**
My system browser (`x-www-browser`) is chrome, but opening a issue pops open a firefox window.

**Please provide following details**
1. JiraCLI Version:
```
$ jira version
(Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="linux/amd64")
```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
```
    Please type your answer here. eg: Cloud
```
3. What operating system are you using? Also mention version.
```
    Please type your answer here. Ubuntu 18.04
```
4. What terminal are you using? Also mention version.
```
rxvt-unicode 9.30-2+b1
```

**To Reproduce**

1. `jira issues list`
2. hit enter on an issue
3. Pops open a browser that isn't necessarily your default

**Expected behavior**
Uses default browser

**Comment by ankitpokhrel** [comment]
Hi @jaymzh, you can override default browser using `JIRA_BROWSER` or `BROWSER` env as described [here](https://github.com/ankitpokhrel/jira-cli/discussions/254).

**Comment by jaymzh** [comment]
@ankitpokhrel you are fast!

Thanks, that's a reasonable work around, but I still think it's a bug. There's a way to call the default browser (x-www-browser) and that should probably be `jira-cli`s default. In my case, I switch my default browser depending on whether I'm working on work stuff or other stuff, and I'd prefer everything follow what my default browser is set to, rather than have to update every tool that can open a tab.

**Comment by ankitpokhrel** [comment]
@jaymzh The current flow is something like this:
- The script first looks for `JIRA_BROWSER` and `BROWSER` env and if any of them is set, the browser is invoked directly. 
- If none of these env is set, it looks for `xdg-open`, `x-www-browser` and `www-browser` in the given order (for linux).

I wonder if `xdg-open` launches default browser in your system?

**Comment by jaymzh** [comment]
Oh interesting. Didn't even think of xdg-open for URLs. Yes, that seems to be set to firefox. I'll set my script to both `update-alternatives` *and* `xdg-settings set`. Thanks, and sorry for the not-actual-bug-report.
