### ISSUE TITLE
404 error: jira issue list --limit=$((1<<31))

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#277]
**Describe the bug**
The upper limit on the `jira issue list --limit` is an undocumented 2147483647; i.e., 2**31 - 1

**Please provide following details**
1. JiraCLI Version:
    ```
    $ jira version
    (Version="v0.3.1-0.20220124201418-5429cbd9d363", GitCommit="", CommitDate="", GoVersion="go1.17.6", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Ubuntu 20.04
    ```
4. What terminal are you using? Also mention version.
    ```
    $ gnome-terminal --version
    # GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
    ```

**To Reproduce**

```
$ jira issue list --plain --limit="$(((1 << 31) - 1))" >/dev/null 2>&1 ; echo $?
0
$ jira issue list --plain --limit="$(((1 << 31) - 0))" ; echo $?
⠹ Fetching issues... 
jira: Received unexpected response '404 Not Found'.
Please check the parameters you supplied and try again.
1
```

**Expected behavior**

Some kind of error message blaming the size of the limit, and not an error message reporting a 404.

**Screenshots**

Not applicable.

**Additional context**

Not applicable.

**Comment by ankitpokhrel** [comment]
This can be one of the minor improvement but I don't see any immediate problem with this. We are not supposed to pass a limit this big and Jira is taking care of it anyway. 

However, I noticed another issue because of how Jira API behaves.

> To manage page size, Jira may return fewer items per page where a large number of fields are requested.

We are not actually getting expected number of results if the response body is huge so `--limit` option seems unreliable.

**Comment by realtime-neil** [comment]
At what point "may" Jira return fewer than the requested quantity? Where is this documented?

**Comment by ankitpokhrel** [comment]
I was referring to [this API doc](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-search/#api-rest-api-3-search-get) (forgot to link it in previous comment, sorry).

![Screen Shot 2022-02-03 at 6 53 39 PM](https://user-images.githubusercontent.com/2364546/152400417-9700cd2e-afbb-44b9-bb42-8ae1ddf87a20.png)

**Comment by realtime-neil** [comment]
@ankitpokhrel okay, I understand. Could you point out where in your source code you're handling the paged responses?

**Comment by ankitpokhrel** [comment]
`jira issue list` invokes `/search` endpoint I linked above and we are passing `maxResults` [here](https://github.com/ankitpokhrel/jira-cli/blob/main/pkg/jira/search.go#L35).

**Comment by ankitpokhrel** [comment]
`limit` flag is replaced with `paginate` in #359
