### ISSUE TITLE
subtask creation not working

### ISSUE THREAD

**Issue by davidsu** [ankitpokhrel/jira-cli#281]
First thanks a lot for the key, that's really nice and useful.

**Describe the bug**
creating a subtask fails. five parent is not passed to the api.

**Please provide following details**
1. JiraCLI Version:
(Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="darwin/amd64")

2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
cloud

3. What operating system are you using? Also mention version.
    macOS Catalina 10.15.7

4. What terminal are you using? Also mention version.
    iTerm 2 Build 3.4.3

**To Reproduce**

given a task or story with id SDK-51, run
`jira issue create -s'the title' -P"SDK-51" -b"the-body" -t'Sub-Task' --no-input`
or whatever similar combination. get an error from the api.
further inspection shows that the body of the call was
`{"update":{},"fields":{"description":"the body","issuetype":{"name":"Sub-Task"},"project":{"key":"SDK"},"summary":"the title"}}`

curling around shows that `{fields: {parent:{key:SDK-51}}}` is missing to make this work.

**Comment by davidsu** [comment]
I found the issue to be a typo here
https://github.com/ankitpokhrel/jira-cli/blob/5429cbd9d36360ac88245a412d3672a1c023a2a9/pkg/jira/issue.go#L20

don't know if that's globally right, my jira expects the type to be `Sub-Task` with capital `T`

**Comment by ankitpokhrel** [comment]
Hi @davidsu, thank you for reporting the issue. The issuetypes were not available in the config when I first created this feature. We have this info in the config now so it would be wise to get it from there.

**Comment by ankitpokhrel** [comment]
@davidsu could you please check the fix and see if it works for you. You can install it with following command.
```sh
go install github.com/ankitpokhrel/jira-cli/cmd/jira@fix-issue-281
```
