### ISSUE TITLE
jira issue list: CREATED and UPDATED column does not match computer time

### ISSUE THREAD

**Issue by heeh** [ankitpokhrel/jira-cli#306]
**Describe the bug**
`jira issue list` does not generate correct time.

**Please provide following details**
1. JiraCLI Version:
    ```(Version="main", GitCommit="5429cbd9d36360ac88245a412d3672a1c023a2a9", CommitDate="2022-01-24T20:14:18+00:00", GoVersion="go1.17.6", Compiler="gc", Platform="darwin/amd64")```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```Jira Server 8.20.1```
3. What operating system are you using? Also mention version.
    ```macOS Monterey 12.2.1```
4. What terminal are you using? Also mention version.
    ```Mac Terminal Version 2.12 (443)```

**To Reproduce**

```jira issue list```

**Expected behavior**
```Jira CREATED and UPDATED time matches the computer time```

**Actual behavior**
```Jira CREATED and UPDATED time is six hours ahead computer time```

**Comment**
Do I have to set up time zone? how?

**Comment by ankitpokhrel** [comment]
@heeh the displayed date time is in UTC. Jira API doesn't support timezone in its endpoints and JQL query. 

Related: [JRACLOUD-17359](https://jira.atlassian.com/browse/JRACLOUD-17359)

**Comment by heeh** [comment]
Thank you @ankitpokhrel I really like the program!
