### ISSUE TITLE
Support for custom field

### ISSUE THREAD

**Issue by vballestra-latch** [ankitpokhrel/jira-cli#340]
If would be nice to be able to show and edit custom fields. Is this feature already supported or are any plans to support it?

**Comment by ankitpokhrel** [comment]
@vballestra-latch this feature is in progress https://github.com/ankitpokhrel/jira-cli/pull/319, you can help by testing and providing feedback.

**Comment by danjee** [comment]
I'm still having issues with this on version 1.1.0
I've regenerated the config file with the init to add the custom fields. Another question rises here, how do you work with multiple projects? 

<img width="1495" alt="Screenshot 2022-09-14 at 09 54 45" src="https://user-images.githubusercontent.com/3084216/190082589-4ef8a62f-8177-4896-a99a-4ced1a42b76a.png">

The config contains the custom fields in question.

<img width="429" alt="Screenshot 2022-09-14 at 09 56 06" src="https://user-images.githubusercontent.com/3084216/190082754-2d870942-e0b3-4c1e-a783-9fae24ef06aa.png">

Thanks, great initiative btw

**Comment by ankitpokhrel** [comment]
Hi @danjee, you need to pass the field name. You can find the [details here](https://github.com/ankitpokhrel/jira-cli/discussions/346). Also, note that not all data type is supported for custom fields.

**Comment by danjee** [comment]
Maybe I'm missing something from the documentation but I'm not passing them ? See first picture?

**Comment by ankitpokhrel** [comment]
You need to pass the name slug. So instead of `--custom=customfield_11780=xyz` it would be `--custom=rollback-strategy=xyz`. You don't have to look for custom field key from Jira. This is explained in the doc I shared above.

**Comment by codesafely** [comment]
I get a `customfield_13743: Field 'customfield_13743' cannot be set. It is not on the appropriate screen, or unknown.` when trying to set story points, `jira issue edit CMP-3655 --no-input --custom story-points=5`

```yaml
- name: Story Points
  key: customfield_10023
  schema:
    datatype: number
```

This 400 is coming from Jira. How can I troubleshoot? is the `number` datatype not supported?

**Comment by whompyjaw** [comment]
How does this work when I want to _**view**_ a custom field in my jira issue? Right now, my `jira view issue PROJECT-#` does not return all the fields that are visible on my jira instance. That command does not have a `--custom` option... So, what am I suppose to do?

**Comment by chauhan17nitin** [comment]
> How does this work when I want to _**view**_ a custom field in my jira issue? Right now, my `jira view issue PROJECT-#` does not return all the fields that are visible on my jira instance. That command does not have a `--custom` option... So, what am I suppose to do?

This same is case with listing issues of sprint
