### ISSUE TITLE
Editing any issue drops the ParentIssue (Epic) Link for Jira Cloud Standard Project

### ISSUE THREAD

**Issue by erichsend** [ankitpokhrel/jira-cli#341]
**Describe the bug**
If I make any edit to an issue, it seems the Epic Link is dropped. 

**Please provide following details**
1. JiraCLI Version:
I changed to 'main' from a relatively recent version and see the issue in both places.
 
 ```
(Version="main", GitCommit="9a435d07e45325d34f4f99799e596bda64e48cf6", CommitDate="2022-03-29T03:04:45+00:00", GoVersion="go1.18", Compiler="gc", Platform="darwin/arm64")

```

3. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.

    ```
    Cloud
    ```
5. What operating system are you using? Also mention version.

```
   macOS Monterey 12.3
```

6. What terminal are you using? Also mention version.

```
    iTerm 2 Build 3.4.15
```

**To Reproduce**

1. `jira issue edit ISSUE-1` for any issue linked to an Epic
2. Edit a field, for example Summary or add a component 
3. Save successfully
4. Open issue in Jira and see the epic link is gone

**Expected behavior**
The Epic Link shouldn't be lost

**Screenshots**

**Additional context**
I tried updating to the main build. I also re-initted jira to get a new config file. I also tried manually verifying the custom fields for epic link and epic name for my Cloud jira, but they matched what was in the jira-cli config file.

Ex:
```
board: ""
epic:
  name: customfield_10005
  link: customfield_10008
installation: Cloud
i
```

**Comment by ankitpokhrel** [comment]
@erichsend Thank you for reporting the issue. This should be fixed with #351. Please feel free to comment if it doesn't work for you with latest change.
