### ISSUE TITLE
JIRA_AUTH_TYPE has no effect

### ISSUE THREAD

**Issue by snogge** [ankitpokhrel/jira-cli#353]
I'm trying to run jira init with JIRA_AUTH_TYPE=bearer, but it does not seem to have any effect

```
export JIRA_AUTH_TYPE=bearer
# Using Personal Access Token
export JIRA_API_TOLKEN=XXXXXXXXXXXXXXX
jira  --debug init
```

Select local, add server address, add username

```
EQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/myself HTTP/1.1
Host: jira.XXX.com
Authorization: Basic XXXXXXXXXXXXXXXXX



RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 403 
Transfer-Encoding: chunked
Connection: keep-alive
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/html;charset=UTF-8
Date: Thu, 28 Apr 2022 13:13:21 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.18.0 (Ubuntu)
Set-Cookie: JSESSIONID=33B72F8A54298D305C919E1283E856D7; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=31536000
Www-Authenticate: OAuth realm="https%3A%2F%2Fjira.XXX.com"
X-Arequestid: 913x21468273x1
X-Asessionid: 1i9r6b2
X-Authentication-Denied-Reason: CAPTCHA_CHALLENGE; login-url=https://jira.XXX.com/login.jsp
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Seraph-Loginreason: AUTHENTICATION_DENIED
X-Xss-Protection: 1; mode=block
```

It looks like the authentication header is wrong.

```
curl --oauth2-bearer XXXXXXXXXXXXXXXX https://jira.XXX.com/rest/api/2/myself 
```

Works and returns the expected JSON response.

**Please provide following details**
1. JiraCLI Version:
   ```
   (Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira Server v8.20.1
    ```
3. What operating system are you using? Also mention version.
    ```
    Debian 10
    ```
4. What terminal are you using? Also mention version.
    ```
    GNOME Terminal 3.30.2 using VTE 0.54.2 +GNUTLS
    ```

**Comment by snogge** [comment]
Thank you, adding it to the config file worked. I'm not a fan of setting this type of environment variables when there is a config file.
I think it would be great if `auth_type:bearer` was added to the config file by the setup command.

**Comment by ankitpokhrel** [comment]
>  I think it would be great if auth_type:bearer was added to the config file by the setup command.

Thank you for the feedback. It may not happen soon but there is a plan to work on a `config` command (similar to `git config`) that will let you control the configurations.

**Comment by TGPSKI** [comment]
Is there an example of a config file somewhere? I am stuck on this problem and without an example I am struggling to create a config file where I can change the auth type.

**Comment by TGPSKI** [comment]
I'll add that running `go install github.com/ankitpokhrel/jira-cli/cmd/jira@latest` did not result in a working binary for bearer token type. When I cloned the repo and ran the makefile directives (build / install), then I was unblocked.
