### ISSUE TITLE
Unable to edit labels on sub-task

### ISSUE THREAD

**Issue by ad8lmondy** [ankitpokhrel/jira-cli#358]
**Describe the bug**
I want to add labels to an existing sub-task.

I tried running:
```
jira issue edit SRE-1267 -lpatching -l'ljw0.xyz.com' --no-input
```
but I get this returned:
```
Error:
  - You can not remove a subtask's parent
```
Running with `--debug` (and removing details), the last response is:
```
RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 400 Bad Request
...
```
If I run the command interactively (by removing the `--no-input` flag), I get the same result.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira Cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
    ```
4. What terminal are you using? Also mention version.
    ```
    VScode in-built terminal, but happens on other terminals too.
    ```

**To Reproduce**

Steps to reproduce the behaviour:
1. See above, in the description. Appears to happen to all my sub-tasks.

**Expected behaviour**
I expect any existing labels on the subtask to be overwritten with the labels I provide on the command-line.
I would not expect to have to specify the parent task - but even if I wanted to, the `edit` command does not seem to have the `--parent` flag as an option.

**Comment by ankitpokhrel** [comment]
Hi @ad8lmondy, could you please check this with the main build? A lot has changed in the main branch. To get the dev release, you can either [compile the source locally](https://github.com/ankitpokhrel/jira-cli#development) or you can use following command (requires go1.16+).

```sh
go install github.com/ankitpokhrel/jira-cli/cmd/jira@main
```

Also, If you are using Homebrew, you can do:

```sh
brew install jira-cli --HEAD
```

**Comment by ad8lmondy** [comment]
Hello,

I used the `go install` method, and running the exact same CLI input on the compiled version: it works!

Thanks for that!
