### ISSUE TITLE
jira issue list --plain

### ISSUE THREAD

**Issue by Tarektouati** [ankitpokhrel/jira-cli#363]
**Describe the bug**

**Please provide following details**
1. JiraCLI Version:
    ```
   (Version="0.3.0", GitCommit="ea53355d5b72994a5b17a63e6e800ce9d8a23f4e", CommitDate="2022-01-09T19:50:19+00:00", GoVersion="go1.17.5", Compiler="gc", Platform="darwin/amd64")
    ```
3. What operating system are you using? Also mention version.
    ```
    Please type your answer here. eg: macOS Montery 12.2.1
    ```
4. What terminal are you using? Also mention version.
    ```
    Please type your answer here. eg: iTerm 2 Build 3.4.15
    ```

**To Reproduce**

1. `jira issue --list --plain  | grep <something>`
3. See nothing  

**Expected behavior**
Be able to grep on jira's issues list. 

**Additional context**
It seems to be the same issue as #223, but with `issue` command. the `--plain` flag keeps the UI loader and interfere with the following command.

**Comment by ankitpokhrel** [comment]
Hi @Tarektouati, this seem to be working fine for me. Could you please try with the [latest beta release](https://github.com/ankitpokhrel/jira-cli/releases/tag/v1.0.0-beta)?

```sh
$ jira issue list --plain | grep test | wc -l
26
```

**Comment by Tarektouati** [comment]
Hey @ankitpokhrel ! it seems that the 1.0.0 version resolves the issue, thanks for your help ! have a great day :)
