### ISSUE TITLE
Jira init non-interactive

### ISSUE THREAD

**Issue by OmarKalloush** [ankitpokhrel/jira-cli#366]
``> Please consider [opening a discussion](https://github.com/ankitpokhrel/jira-cli/discussions/categories/ideas) in `ideas` category if applicable. Your feature will be prioritized on based on the number of votes.  

**Is your feature request related to a problem? Please describe.**

I'm trying to use jira cli in a pipeline and i was wondering if i could init with a non-interactive way

**Describe the solution you'd like**

A flag to pass the data to `jira init` command

**Describe alternatives you've considered**

using curl command to create issue and edit them using Jira REST API

**Comment by realtime-neil** [comment]
Concur 100% --- fully _every_ sub-command should be non-interactive.

**Comment by pdusen** [comment]
FWIW, I have worked around this by creating a a templated version of `~/.config/.jira/.config.yml` and deploying it to the proper location on my build agents when they begin a job that requires jira-cli.

    installation: Local
    login: $JIRA_API_USER
    project:
      key: $MATCHING_PREFIX
      type: ""
    server: $JIRA_URL

Still, not ideal. It should definitely be possible to run `init` in a non-interactive fashion.

**Comment by ankitpokhrel** [comment]
I am with you folks on this! This one is on my to-do list and I will work on it. PRs are welcome in the meantime.
