### ISSUE TITLE
For 'jira issue edit', editing only a custom field with --no-input results in "✗ Nothing to update"

### ISSUE THREAD

**Issue by OneGeek** [ankitpokhrel/jira-cli#390]
**Describe the bug**

I am writing a tool that needs to modify a jira issue custom field, among other tasks. I want to use a command of the form
`jira issue edit EX-123 --custom my-field=foo --no-input`
However, that command results in the output `✗ Nothing to update`

If I omit `--no-input` and just hit enter to accept the current summary and description and choose 'submit', it works as expected and the custom field is updated.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.0.0-beta.1", GitCommit="85d8a7ec5a376a55e50b8d14e09788f837ff4233", CommitDate="2022-05-29T17:33:26+00:00", GoVersion="go1.18.1", Compiler="gc", Platform="windows/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Windows 11 Pro - Version 21H2 (OS Build 22000.739)
    ```
4. What terminal are you using? Also mention version.
    ```
    Windows Terminal v1.13.1143
    ```

**To Reproduce**

This is what I want to do that doesn't work
1. Run `jira issue edit EX-123 --custom my-field=foo --no-input`
2. See `✗ Nothing to update`

The interactive version works as expected
1. Run `jira issue edit EX-123 --custom my-field=foo`
2. Press enter, see `? Summary (Test Story)`
3. Press enter, see `? Description [(e) to launch notepad, enter to skip]`
4. Press enter, see
```
? Summary Test Story
? Description <Received>
? What's next?  [Use arrows to move, type to filter]
> Submit
  Add metadata
  Cancel
```
5. Press enter, see
``` 
✓ Issue updated
https://jira.example.com/browse/EX-123
```

**Expected behavior**
1. Run `jira issue edit EX-123 --custom my-field=foo --no-input`
5. See
``` 
✓ Issue updated
https://jira.example.com/browse/EX-123
```

**Comment by ankitpokhrel** [comment]
Looks like a bug, thanks for reporting!
