### ISSUE TITLE
Formatting issue or missing char set? 

### ISSUE THREAD

**Issue by dofinn** [ankitpokhrel/jira-cli#393]
**Describe the bug**

jira view issue fails to display correctly 

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="v0.0.0-dev", GitCommit="", CommitDate="", GoVersion="go1.18.2", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    on-premise, unsure of version 
    ```
3. What operating system are you using? Also mention version.
    ```
    Fedora 36
    ```
4. What terminal are you using? Also mention version.
    ```
    alacritty --version
    alacritty 0.10.1
    ```

**To Reproduce**

1. jira view with above setup

**Expected behavior**

Output is readable 

**Screenshots**

```
ESC[38;5;252mESC[0mESC[38;5;252mESC[0m  ESC[38;5;252m🐞 Bug  🚧 Closed  ⌛ Thu, 16 Jun 22
``` 
**Additional context**

**Comment by ankitpokhrel** [comment]
Hi @dofinn, It seem to be working fine for me with Alacritty 0.10.1 on macOS. I think this is something related to your shell config.

Possibly related: #213 #291 #367

Also you seem to be using old version of the tool. Try using the [latest beta release](https://github.com/ankitpokhrel/jira-cli/releases/tag/v1.0.0-beta.1).

**Comment by dofinn** [comment]
Hi @ankitpokhrel - i am using a locally built version due to https://github.com/ankitpokhrel/jira-cli/pull/343. 

additionally https://github.com/ankitpokhrel/jira-cli/discussions/367 appears to resolve my issues :+1:

**Comment by ankitpokhrel** [comment]
Closing this since there are related open issues.
