### ISSUE TITLE
Getting 302 error when trying to list Issues or Epics

### ISSUE THREAD

**Issue by bs7280** [ankitpokhrel/jira-cli#402]
**Describe the bug**
Im using JIRA-CLI for the first time, I am able to login with a Personal Auth Token and view all projects and boards no problem. BUT when I try to do `jira issue list` or `jira epic list` I get this error message:

```
jira: Received unexpected response '302 '.
Please check the parameters you supplied and try again.
```
I assume this is an HTTP redirect error? 

Im not sure how else to get more information / logs / debug mode but happy to help debug this.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.0.0-beta.2", GitCommit="f32f2d8b3bbb0d7f8de9d9848c62e22f75cdcca0", CommitDate="2022-06-20T15:55:34+00:00", GoVersion="go1.18.1", Compiler="gc", Platform="darwin/arm64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Cloud version 8.22.2
    ```
3. What operating system are you using? Also mention version.
    ```
    MacOs Monterey 12.2.1 (M1)
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm 2 Build 3.4.15
    ```

**To Reproduce**

1. configure jira-cli via `jira init` after setting two env vars: 
   * `JIRA_API_TOKEN=<personal access token>`
   * `JIRA_AUTH_TYPE=bearer`
3. selected my teams project
4. selected my teams board
5. init successful
6. run `jira issue list`
   * get error message shown above
7. run `jira epic list`
   * get error message shown above

**Expected behavior**
JIRA-CLI lists out epics / issues as expected

**Screenshots**
N/a

**Additional context**
N/a as I don't know how to access logs / debug mode to provide more info

**Comment by ankitpokhrel** [comment]
Hi @bs7280, is your setup under a VPN/proxy? Also, could you send the debug output of `jira issue list --debug` (Make sure to redact sensitive information).

**Comment by bs7280** [comment]
Thanks @ankitpokhrel, so I am on a VPN (which im connected to) but getting projects and board names worked fine. 

The main info I see from the --debug output is its redirecting me to the login page: 
`/login.jsp?os_destination=https://gojira.redactedcompany.com/rest/api/3/search?jql=project%3D%22DEV%22+ORDER+BY+created+DESC&startAt=0&maxResults=100`

full debug output with name, company, and tokens removed

```
Using config file: /Users/redactedname/.config/.jira/.config.yml
JQL: project="DEV" ORDER BY created DESC
⠋ Fetching issues...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/3/search?jql=project%3D%22DEV%22+ORDER+BY+created+DESC&startAt=0&maxResults=100 HTTP/1.1
Host: gojira.redactedcompany.com
Authorization: Bearer token-redacted



RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 302
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/html;charset=UTF-8
Date: Tue, 28 Jun 2022 18:11:04 GMT
Location: /login.jsp?os_destination=https%3A%2F%2Fgojira.redactedcompany.com%2Frest%2Fapi%2F3%2Fsearch%3Fjql%3Dproject%253D%2522DEV%2522%2BORDER%2BBY%2Bcreated%2BDESC%26startAt%3D0%26maxResults%3D100
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: JSESSIONID=redacted; Path=/; Secure; HttpOnly
Set-Cookie: atlassian.xsrf.token=redacted; Path=/; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000
X-Arequestid: 731x14323623x2
X-Asessionid: jg8ete
X-Ausername: Redactedname%40redactedcompany.com
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Seraph-Loginreason: OK
X-Xss-Protection: 1; mode=block
Content-Length: 0


jira: Received unexpected response '302 '.
Please check the parameters you supplied and try again.
```

Thanks

**Comment by ankitpokhrel** [comment]
> getting projects and board names worked fine

Its strange that this worked but other API calls didn't. I wonder does your token has permissions need to list issues. You will only get this error if you don't have enough permission to call the endpoint. Do you get response with the direct API call?

```
curl --request GET \
  -H "Authorization: Bearer $JIRA_API_TOKEN" \
  --url 'https://<SERVER>.example.net/rest/api/3/search?jql=project%3D%22DEV%22+ORDER+BY+created+DESC&startAt=0&maxResults=100'
```

**Comment by ankitpokhrel** [comment]
Hi @ankitpokhrel, that's a local installation but it seems like you've configured `jira-cli` for cloud installation. Cloud installation are instances managed by Atlassian under atlasian.net. Please run `jira init` again and choose installation type as `Local` to configure your setup.
