### ISSUE TITLE
Unassigning through the interactive command ‘jira issue assign’ doesn’t work

### ISSUE THREAD

**Issue by hugocm93** [ankitpokhrel/jira-cli#404]
`jira issue assign ‘issue#’` doesn’t work when I choose `No-one (unassign)`. I get a “internal server error” with code 500. However if I use `jira issue assign ‘issue#’ x`, it works.

**Please provide following details**
1. JiraCLI Version:
    ```
    1.0.0-beta.2
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    On-premise jira server, don’t know how to check it’s version.
    ```
3. What operating system are you using? Also mention version.
    ```
    Centos6
    ```
4. What terminal are you using? Also mention version.
    ```
    Termius for iOS 4.11.4
    ```

**To Reproduce**

See description.

**Expected behavior**
That choosing “No-one” behaves the same way as using the non interactive version with the `x` arg.

**Comment by ankitpokhrel** [comment]
Should be fixed with #404. Thank you for reporting the issue!
