### ISSUE TITLE
JIRA issue list command not showing the highlighted issue on Windows

### ISSUE THREAD

**Issue by PersistentCoder7** [ankitpokhrel/jira-cli#415]
While browsing through the issue list on windows, we cannot see the selection bar highlighting, making it very difficult to identify the currently selected item. Only the heading is clearly highlighted in blue.

**Comment by TGPSKI** [comment]
Same issue on Manjaro Linux

jira-cli v1.0.0
zsh shell in Konsole
Kernel 5.18.10

**Comment by TGPSKI** [comment]
I think this is somewhere around here: https://github.com/ankitpokhrel/jira-cli/blob/main/pkg/tui/table.go#L258

**Comment by TGPSKI** [comment]
I would expect to see SetSelectable and SetFixed called somewhere in Issues.go render method: https://github.com/ankitpokhrel/jira-cli/blob/main/internal/view/issues.go#L41

cc: rivo's docs on table selections: https://pkg.go.dev/github.com/rivo/tview#hdr-Selections

**Comment by ankitpokhrel** [comment]
@PersistentCoder7 @TGPSKI you should be able to customize the UI for highlighted issue once https://github.com/ankitpokhrel/jira-cli/pull/419 is merged. Feel free to try it and report any issues, you can install the changes using following command.

```
go install github.com/ankitpokhrel/jira-cli/cmd/jira@feat-selection-highlight
```

**Comment by TGPSKI** [comment]
@ankitpokhrel this works exceptionally well.

I was scratching my head for a minute looking for the config file, but found it in the help output from running `$ jira`

**Comment by PersistentCoder7** [comment]
@ankitpokhrel  Can you share the latest version of the windows executable containing the pull request? I can test and confirm.

**Comment by ankitpokhrel** [comment]
Hi @PersistentCoder7, the changes are merged and available in the main branch. For now you either need to [compile it locally](https://github.com/ankitpokhrel/jira-cli#development) or use following methods to install. Changes will be available in the new release possibly in a few weeks.

With [Golang](https://go.dev/)

```sh
go install github.com/ankitpokhrel/jira-cli/cmd/jira@main
```

With [docker](https://www.docker.com/)

```sh
docker pull ghcr.io/ankitpokhrel/jira-cli:main
```

**Comment by PersistentCoder7** [comment]
I was able to test the fix, and everything works flawlessly. Thanks, @ankitpokhrel.
