### ISSUE TITLE
Create Metadata needs to be updated to work with jira 9

### ISSUE THREAD

**Issue by svzieg** [ankitpokhrel/jira-cli#425]
**Describe the bug**
The current create Meta client request calles the api for jira versions below 8.,4 

https://github.com/ankitpokhrel/jira-cli/blob/ebc9e0e2e459a3ec7f1c1779f1294f69433175d3/pkg/jira/createmeta.go#L33-L45

after 8.4  the url changes to 
```
<server>/rest/api/2/issue/createmeta/{projectIdOrKey}/issuetypes
```

https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/

**Please provide following details**
1. JiraCLI Version:
    ```
       (Version="1.0.0", GitCommit="e94433858ee31e16d4b41c14032864f3c5361115", CommitDate="2022-06-23T06:35:37+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="linux/amd64")
    ``` 

2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira Server v9.0.0

    ```
    3. What operating system are you using? Also mention version.
    ```
        Linux Manjaro    ```

4. What terminal are you using? Also mention version.
    ```
    kitty
    ```
    
**To Reproduce**

Steps to reproduce the behavior:
1. jira init --debug (with local installation of jira 9)
3. See error (Http status: 404  => {"errorMessages":["Issue Does Not Exist"],"errors":{}})

**Expected behavior**
jira init should also work on jira 9

**Screenshots**
<!--- If applicable, add screenshots to help explain your problem. --->

**Additional context**
<!--- Add any other context about the problem here. --->

**Comment by ankitpokhrel** [comment]
Hi @svzieg, this should be fixed with #447. Thanks for reporting!
