### ISSUE TITLE
Support for multiple Jira instances.

### ISSUE THREAD

**Issue by wstewarttennes** [ankitpokhrel/jira-cli#434]
**Is your feature request related to a problem? Please describe.**

I work with multiple Jira instances for work/personal life. Would LOVE to be able to access them all from either one jira-cli installation or across multiple iTerm profiles. Right now, because there is only one configuration file, I can't setup multiple Jira instances.

**Describe the solution you'd like**

option 1: Add support for configuration files with multiple Jira instances or pointing to multiple .netrc files. Then, add a JIRA_INSTANCE environment variable that I could set at launch that defines which jira instance I'm using.

options 2: Add support for configuration files with multiple Jira instances and add a flag in the cli that specifies which instance to use.

**Comment by ankitpokhrel** [comment]
Hi @wstewarttennes, there is a `--config/-c` flag available that you can use to target different Jira instances. You can also use `XDG_CONFIG_HOME` env for the same purpose.
