### ISSUE TITLE
`--plain` has no effect when used with `epic list`

### ISSUE THREAD

**Issue by ebrodsky-abst** [ankitpokhrel/jira-cli#443]
**Describe the bug**
`jira epic list --plain` displays a table instead of plaintext output

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.0.0", GitCommit="e94433858ee31e16d4b41c14032864f3c5361115", CommitDate="2022-06-23T06:35:37+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="darwin/arm64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    On-premise; v8.20.10
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS Monterey 12.5
    ```
4. What terminal are you using? Also mention version.
    ```
    Alacritty v0.10.1
    ```

**To Reproduce**

1. `jira epic list --plain`

**Expected behavior**

Expecting to see a plaintext list of epics

**Comment by ankitpokhrel** [comment]
You cannout use `--plain` in preview layout, you need to:

```sh
jira epic list --table --plain
```
