### ISSUE TITLE
Add/remove weblink to issue

### ISSUE THREAD

**Issue by xelite** [ankitpokhrel/jira-cli#446]
# Web link in issue. 

I want to create web link to external resources, eg. monitoring systems. Optional set `--link-text` with default vault same as url.

### `jira issue link ISSUE-123 "http://my.url" "WebLink" [--link-text "check this"] `

![image](https://user-images.githubusercontent.com/5921448/186739228-082555d3-767c-4dc2-9bac-46869ee6429a.png)

**Comment by Syd7** [comment]
not sure if this feature is confirmed or not, would it be possible to work on it as part of hacktoberfest?
