### ISSUE TITLE
How can I select multiple statuses?

### ISSUE THREAD

**Issue by emmanuelnk** [ankitpokhrel/jira-cli#466]
I'd like to see all issues that neither DONE nor REJECTED e.g.

```bash
jira issue list -s~"Done" -s~"Rejected" -a$(jira me)
```

But this doesn't work -- it always takes just the last filter. I can't see this anywhere in the documentation but I think this is a common scenario. If there isn't a way to do this, I'll open a feature request.

**Comment by ankitpokhrel** [comment]
Hi @emmanuelnk, `-s` option only takes a single value at the moment so the command above won't work. You can do something like below to filter issues in multiple statuses.

```sh
jira issue list -q"status not in (Done, 'To Do')"
```

**Comment by emmanuelnk** [comment]
Thank you that works! Closing

**Comment by binarious** [comment]
Doesn't seem to be working with `--show-all-issues` and `sprint list`:
```
jira sprint list 14581 -q"status in (To Do, Open)" --show-all-issues
```
