### ISSUE TITLE
Create issues in the _board_, rather than the _backlog_

### ISSUE THREAD

**Issue by lambwaves** [ankitpokhrel/jira-cli#470]
Howdy!

I love your tool, but I'm having a bit of a problem, most likely due to my unfamiliarly with Jira. 

My workflow is hearing about a bug in slack, then creating an issue in Jira; which I need for opening a pull request and for time tracking. 

One small issue I've run into today has been getting created issues to show up in the _board_, as issues created with this tool show up in the _backlog_.

Here is a screenshot, showing a new issue in the _backlog_, and where I drag the issue to get it on the _board_

<img width="785" alt="Screenshot 2022-09-14 at 11 56 49 AM" src="https://user-images.githubusercontent.com/106105639/190240540-eb817068-d14a-4ee8-8d6c-1de1c8326be9.png">

Looking at the network requests, I'm seeing a PUT to `/rest/greenhopper/1.0/xboard/assignToListAndRank` with this data, truncated. 
'{"issueKeys":["XYZ"] ... "target":"BOARD"}'

Searching the code of this repository, I'm not seeing the results for assign to list, or assignToListAndRank. Is moving an issue to the _board_ possible with the API, or with JQL? If not, I can remember to manually move the issue, but my dream is I never open jira again.

**Comment by ankitpokhrel** [comment]
@lambwaves Issue is tied to the project. 

For scrum boards, the task will be available in the backlog and you need to move it your board from backlog. I don't thin you can select board when creating issues from the UI too.

If your board is created with a saved filter, the issue will show up in your board if it matches the filter the board is using. Check what filters you are using in the board and create issues to fulfill those criteria.
