### ISSUE TITLE
jira sprint list does not accept passing an arbitrary project string

### ISSUE THREAD

**Issue by anavarre** [ankitpokhrel/jira-cli#474]
**Describe the bug**

I'm using the default configuration file and my default project string is `IDE`

```
-p, --project string   Jira project to look into (defaults to /Users/myusername/.config/.jira/.config.yml)
```

This means whether or not I pass `-pIDE` to the `jira sprint list` commands it properly returns my items.

```
❯ jira sprint list -pIDE --current --plain --no-headers --paginate 1
Story	IDE-2581	Sanitized ticket title	Open
```

But now, if I change the project string to use something different, say `DIS` (which very much exists), then it fails.

```
❯ jira sprint list -pDIS --current --plain --no-headers --paginate 1

✗ No result found for given query in project "DIS"
```

However we can see below it very much exists when using another command, say `jira issue list`.

```
❯ jira issue list -pDIS --plain --no-headers --paginate 1
Epic	DIS-546	Another sanitized ticket title	Open
```

If I'm trying to query the API directly, we can see the active sprint in the `DIS` project exists.

```
❯ curl --request GET \
  -H "Authorization: Bearer $JIRA_API_TOKEN" \
  --url 'https://mydomain.com/rest/agile/1.0/sprint/7130/issue?jql=project=DIS'
{"expand":"schema,names","startAt":0,"maxResults":50,"total":16,"issues":[{"expand":"operations,versionedRepresentations,editmeta,changelog,renderedFields","id":"12355065
(snip)
```

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.1.0", GitCommit="3b93e147eac468ad985bdece27469153b4bb2814", CommitDate="2022-08-14T08:10:40+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="darwin/arm64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
   Jira Server v8.20.10#820010-sha1:ace47f9
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS Monterey 12.5.1 (21G83)
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm 2 Build 3.4.16
    ```

**To Reproduce**

See above.

**Expected behavior**
`jira sprint list -p<key>` works as expected

**Screenshots**
N/A

**Additional context**
I did try to have a whitespace, e.g. `-p DIS` but it didn't make any difference.

**Comment by ankitpokhrel** [comment]
Hi @anavarre, sprints do not relate to a project but the boards. `jira issue list` gets [all sprint in the configured board](https://developer.atlassian.com/cloud/jira/software/rest/api-group-board/#api-rest-agile-1-0-board-boardid-sprint-get). So the project filter won't do anything in this case.
