### ISSUE TITLE
Error: open Light: no such file or directory

### ISSUE THREAD

**Issue by yermulnik** [ankitpokhrel/jira-cli#476]
**Describe the bug**

Running any CLI command to query Jira results in `Error: open Light: no such file or directory` error

**Please provide following details**
1. JiraCLI Version:
```
(Version="1.1.0", GitCommit="3b93e147eac468ad985bdece27469153b4bb2814", CommitDate="2022-08-14T08:10:40+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="linux/amd64")
```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
```
Cloud
```
3. What operating system are you using? Also mention version.
```
Ubuntu 20.04.5 LTS
```
4. What terminal are you using? Also mention version.
```
mlterm version 3.8.9
```

**To Reproduce**

1. Setup `jira-cli`
2. Run e.g. `jira issue list` or any other command to query Jira API
3. See error `Error: open Light: no such file or directory`

**Expected behavior**

Jira CLI returns result instead of error.

**Screenshots**

None

**Additional context**

```shell
> jira issue list
⠹ Fetching issues...
Error: open Light: no such file or directory
```

**Comment by vydyas** [comment]
I can work on this issue as part of hacktoberfest.

**Comment by yermulnik** [comment]
Discarding this issue as it came up to be local-to-me error via `GLAMOUR_STYLE="Light"` var exported into env (https://github.com/charmbracelet/glamour#styles). Not sure why it stopped recognising `Light` as correct value despite being listed at https://github.com/charmbracelet/glamour/tree/master/styles/gallery 🤔
