### ISSUE TITLE
keychain password must be in 'login' keychain, not 'iCloud'

### ISSUE THREAD

**Issue by bobobox** [ankitpokhrel/jira-cli#484]
### Discussed in https://github.com/ankitpokhrel/jira-cli/discussions/356

<div type='discussions-op-text'>

<sup>Originally posted by **ankitpokhrel** April 30, 2022</sup>

### 3. Keychain password manager

Add a new password item entry with an item name `jira-cli` and account name as your jira username/email.

</div>

The above shoud note that the iCloud keychain is not supported. I initially tried adding it there and it was not recognized. I had to move it to the local 'login' keychain for it to be recognized.

**Comment by ankitpokhrel** [comment]
Updated, thank you!
