### ISSUE TITLE
sprint list does not accept limit.

### ISSUE THREAD

**Issue by stobias123** [ankitpokhrel/jira-cli#486]
**Describe the bug**
Limit flag doesn't work for sprints

**Please provide following details**
1. JiraCLI Version:
```
(Version="request-222", GitCommit="19bc454d9b27269ad72e638688a450f0765b3ff6", CommitDate="2022-03-25T03:39:41+00:00", GoVersion="go1.17.2", Compiler="gc", Platform="darwin/amd64")
```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
```
cloud
```
3. What operating system are you using? Also mention version.
```
osx
```
4. What terminal are you using? Also mention version.
```
iterm
```

**To Reproduce**

```
jira sprint list --table --plain --columns key,summary --limit 1 --no-headers
```

**Expected behavior**
I only want 1 result to be returned. I get 50
```
$ jira sprint list --table --plain --columns key,summary --limit 1 --no-headers | wc -l 
50
```

**Screenshots**

**Additional context**

**Comment by dhiemaz** [comment]
After checking the code, I think this is not an issue but more of to feature request as in the sprint list there is no limit flag.

**Comment by dhiemaz** [comment]
there is no limit flag, if you want to limit result, use paginate flag

command example
```
 jira sprint list --table --plain --columns key,summary --paginate 1 --no-headers
```

testing result
```
$ jira sprint list --table --plain --columns key,summary --paginate 1 --no-headers
1       MP Sprint 1     2022-10-27 19:43:40     2022-11-10 19:43:32             active
```

**Comment by ankitpokhrel** [comment]
Hi @stobias123, you are still using the temporary dev version `request-222`. Please upgrade to the [latest release](https://github.com/ankitpokhrel/jira-cli/releases) and use `--paginate` option as @dhiemaz suggested.
