### ISSUE TITLE
Zsh complition file installs into wrong directory. 

### ISSUE THREAD

**Issue by snpefk** [ankitpokhrel/jira-cli#487]
**Describe the bug**
In my case, it was installed into `~/.oh-my-zsh/plugins/aws`. I guess `.oh-my-zsh` somehow affects `fpath` in unexpected way. 

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="v0.0.0-dev", GitCommit="", CommitDate="", GoVersion="go1.19", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira on-premise v8.22.0
    ```
3. What operating system are you using? Also mention version.
    ```
    Linux 5.18.19-3-MANJARO
    ```
4. What terminal are you using? Also mention version.
    ```
    alacritty 0.10.1 ()
    ```

**To Reproduce**

1. Execute `jira completion zsh > "${fpath[1]}/_jira"`  

**Expected behavior**
I don't know where it suppose to install, but I'm sure it's the wrong place :) 

**Screenshots**
:camera: 

**Additional context**

Here is the log of mine `fpath`:
```
~/.oh-my-zsh/plugins/aws
~/.oh-my-zsh/plugins/gradle-completion
~/.oh-my-zsh/plugins/kubectl
~/.oh-my-zsh/plugins/colored-man-pages
~/.oh-my-zsh/plugins/docker
~/.oh-my-zsh/plugins/rust
~/.oh-my-zsh/plugins/virtualenvwrapper
~/.oh-my-zsh/plugins/pip
~/.oh-my-zsh/plugins/git
~/.oh-my-zsh/functions
~/.oh-my-zsh/completions
~/.oh-my-zsh/cache/completions
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/Math
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle
```

**Comment by ankitpokhrel** [comment]
Hi @snpefk, Thank you for reporting this. For `macOS` it should be the following command:

```sh
jira completion zsh > /usr/local/share/zsh/site-functions/_jira
```

**Comment by snpefk** [comment]
Thanks you for fix, but it's still misleading docs. I'm on **Linux** and if I follow updated docs code completion would be installed in the wrong directory.

**Comment by ankitpokhrel** [comment]
I see, thanks. The `fpath[1]` will take first directory available in `fpath`, in my case it is `docker-compose`. To make it work with fpath we will need to add custom directory to fpath and add the auto completion there. Since it involves a few steps I will stick with recommending `jira completion zsh > /usr/share/zsh/site-functions/_jira` in help which seem to be working for both mac and linux.
