### ISSUE TITLE
Expand `jira issue list --status` to include querying for issues of different status

### ISSUE THREAD

**Issue by ScriptAutomate** [ankitpokhrel/jira-cli#488]
> Please consider [opening a discussion](https://github.com/ankitpokhrel/jira-cli/discussions/categories/ideas) in `ideas` category if applicable. Your feature will be prioritized on based on the number of votes.  

**Is your feature request related to a problem? Please describe.**

I can only list issues assigned to me with either any status, or a single status type.

**Describe the solution you'd like**

I'd like to view all issues assigned to me that are `Blocked` and `In Progress`, for example, with results in the same table without having to run two separate `jira` commands.

```bash
jira issue list --assignee scriptautomate --status Blocked,'In Progress'
```

**Describe alternatives you've considered**

Not sure what other alternative there would be.

**Comment by dhiemaz** [comment]
@ankitpokhrel, I will handle this feature.

**Comment by ankitpokhrel** [comment]
@ScriptAutomate You can use following command as a workaround until this feature gets released.

```sh
jira issue list -q "status in (Done, 'In Progress')"
```
