### ISSUE TITLE
Please consider releasing arm docker images (m1 mac)

### ISSUE THREAD

**Issue by comjf** [ankitpokhrel/jira-cli#501]
Hello,

Excited about the possibility of this project! I just dove right in on your README and the docker step doesn't work because of platform versions. I'm hoping i can get around it using a different installation method (likely brew) but thought I'd throw a quick note here regardless (doesn't look like this was discussed in an existing issue).

Thanks!

Trace:
```
➜  ~ docker run -it --rm ghcr.io/ankitpokhrel/jira-cli:latest

Unable to find image 'ghcr.io/ankitpokhrel/jira-cli:latest' locally
latest: Pulling from ankitpokhrel/jira-cli
213ec9aee27d: Pull complete
688a9c58bab8: Pull complete
4f4fb700ef54: Pull complete
377ada03bea0: Pull complete
Digest: sha256:9b65880d3391a3f442c53d5998df3e8a7e6d0decc708e1809177927af1e9cb0a
Status: Downloaded newer image for ghcr.io/ankitpokhrel/jira-cli:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by ankitpokhrel** [comment]
Hi @comjf, this is done in #508 and image for the next release will be available for arm. Thanks for taking the time to report this!
