### ISSUE TITLE
Can't pip jira sprint list --plain

### ISSUE THREAD

**Issue by Roobxyz** [ankitpokhrel/jira-cli#504]
I'd like to use the jira CLI to select a sprint and assign it to a variable but cannot redirect the output of sprint.

For issues, I can run the below and parse the resulting table in shell:
```
jira issue list  --plain | cat
TYPE	KEY		SUMMARY			STATUS
Story	A-100	        Ticket summary	        In Review
Epic	A-1	        Epic Summary	        In Progress
```

But cannot run the equivalent `sprint` command
```
jira sprint list  --plain | cat
# Menu appears instead :( 
```

Both commands should behave the same so that we can pipe the output of both.

**Comment by ankitpokhrel** [comment]
@Roobxyz `jira issue list` and `jira epic list` uses preview mode by default. You can list them in table view and use the plain option.

```sh
jira sprint list --table --plain | less
```

**Comment by Roobxyz** [comment]
Perfect -- thank you!
