### ISSUE TITLE
Resolution flag in move issue not working

### ISSUE THREAD

**Issue by markpalantoni** [ankitpokhrel/jira-cli#514]
Great package! Thanks for maintaining.

Move issue with the -R flag is not working for me e.g. 
`jira issue move CPD-5024 'Production' -RDone`

The Github documentation says:

# Set resolution to fixed and assign to self while moving the issue
$ jira issue move ISSUE-1 Done -RFixed -a$(jira me)

However, the CLI documentation only lists --help and --web as available flags for `move`.

Is the -R flag on `move` still supported?

**Comment by ankitpokhrel** [comment]
Hi @markpalantoni, this feature is not released yet. If you wish to use it you'll have to use the main branch. For that, you can use following methods.

```sh
// Using docker
$ docker pull ghcr.io/ankitpokhrel/jira-cli:main

// With golang
$ go install github.com/ankitpokhrel/jira-cli/cmd/jira@main

// With homebrew
$ brew tap ankitpokhrel/jira-cli
$ brew install jira-cli --HEAD
```

I will make new release in a few weeks.

**Comment by markpalantoni** [comment]
Great thank you @ankitpokhrel!

**Comment by ankitpokhrel** [comment]
New release [v1.2.0](https://github.com/ankitpokhrel/jira-cli/releases/tag/v1.2.0) is available now.
