### ISSUE TITLE
Jira API changed

### ISSUE THREAD

**Issue by max06** [ankitpokhrel/jira-cli#515]
**Describe the bug**

`./jira init` fails when looking for issuetypes and fields due to a changed jira api

**Please provide following details**
1. JiraCLI Version: 
```
(Version="1.1.0", GitCommit="3b93e147eac468ad985bdece27469153b4bb2814", CommitDate="2022-08-14T08:10:40+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="linux/amd64")
```

3. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira Server v9.3.1
    ```
4. What operating system are you using? Also mention version.
    ```
    Debian Bullseye container
    ```
5. What terminal are you using? Also mention version.
    ```
    VSCode integrated terminal
    ```

**To Reproduce**

1. run `jira init`
2. ...
3. See error
```
? Default board: None
⠙ Configuring metadata. Please wait...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/issue/createmeta?projectKeys=OS&expand=projects.issuetypes.fields HTTP/1.1
Host: redacted
Authorization: Bearer redacted



RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 404 
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, no-transform
Content-Security-Policy: sandbox
Content-Type: application/json;charset=UTF-8
Date: Thu, 01 Dec 2022 14:04:05 GMT
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: JSESSIONID=redacted; Path=/; HttpOnly
Set-Cookie: atlassian.xsrf.token=redacted; Path=/
Strict-Transport-Security: max-age=63072000
X-Arequestid: 844x6040334x2
X-Asessionid: 1xix1ze
X-Ausername: redacted
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Seraph-Loginreason: OK
X-Xss-Protection: 1; mode=block


✗ Received unexpected response '404 ' from jira. Please try again.
```
**Expected behavior**

It should not fail.

**Additional context**

Jira recently updated some apis including breaking changes.
https://docs.atlassian.com/software/jira/docs/api/REST/9.4.0/#api/2/issue-getCreateIssueMetaProjectIssueTypes
https://docs.atlassian.com/software/jira/docs/api/REST/9.4.0/#api/2/issue-getCreateIssueMetaFields

The url schema now uses the project ID or Key in the path instead as a parameter.

**Comment by ankitpokhrel** [comment]
Hi @max06, support for Jira API v9 was added in #447 but its not released yet. If you wish to help with the testing, you can install unrelased version using one of the following methods.

```sh
// Using docker
$ docker pull ghcr.io/ankitpokhrel/jira-cli:main

// With golang
$ go install github.com/ankitpokhrel/jira-cli/cmd/jira@main

// With homebrew
$ brew tap ankitpokhrel/jira-cli
$ brew install jira-cli --HEAD
```

I will make new release in a few weeks.

**Comment by max06** [comment]
Count me in! I'll report issues if I find them.

**Comment by max06** [comment]
Init worked! Closing here 🙇🏼 

Thx a lot, and awesome reaction time!

**Comment by stkrzysiak** [comment]
I'm seeing this exact issue right now on current HEAD, but also saw it with a regular homebrew install(which I'm assuming rolled in that fix from december).  Did this somehow break, and what info can I provide, building it locally in the meantime...

**Comment by stkrzysiak** [comment]
This is something specific to the jira instance I'm using because a curl results in the same issue that `GetCreateMeta` runs into, when hitting the path ``/issue/createmeta?projectKeys=<redacted>&expand=projects.issuetypes.fields`

```json
{"errorMessages":["Issue Does Not Exist"],"errors":{}}
```

**Comment by stkrzysiak** [comment]
The issue for other having this problem is the instance I was using is a jira-server instance, which doesn't support issue/createmeta but rather: [`rest/api/latest/field`](https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/field)

**Comment by stkrzysiak** [comment]
All of my grief these past few hrs could have been avoided by selecting a "Local" instead of a cloud install. Motion to rename "Local" prompt to "Local(Jira Server)" @ankitpokhrel When I saw local i figured it meant a server running on my localhost :/
