### ISSUE TITLE
Allow default editor to be overridden for Windows

### ISSUE THREAD

**Issue by damnlogin** [ankitpokhrel/jira-cli#523]
Currently there is no way to override default editor when editing issue description on Windows as the code [here](https://github.com/ankitpokhrel/jira-cli/blob/94e8e01b2ea1fb1492b995278e44ad9e5d061d65/pkg/surveyext/editor.go#L23-L24) clearly states that if OS is windows - the editor is notepad.

Please let environment variable EDITOR override the default choice.

Here is the suggested change:

```go
func init() {
	if runtime.GOOS == "windows" {
		defaultEditor = "notepad"
        }
	
	if j := os.Getenv("JIRA_EDITOR"); j != "" {
		defaultEditor = j
	} else if v := os.Getenv("VISUAL"); v != "" {
		defaultEditor = v
	} else if e := os.Getenv("EDITOR"); e != "" {
		defaultEditor = e
	}
}
```

**Comment by ankitpokhrel** [comment]
This should be fixed with #524. Thanks for reporting!
