### ISSUE TITLE
302 Redirects Not Followed

### ISSUE THREAD

**Issue by timfallmk** [ankitpokhrel/jira-cli#527]
**Describe the bug**
`jira-cli` doesn't follow redirect's when presented with 302's.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.2.0", GitCommit="9d8a0afd75b68aa519367f93c240429117cc4090", CommitDate="2022-12-16T10:53:08+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="darwin/arm64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    On prem. JiraVersion value=8.20.14
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS 13.1
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm2 Build 3.5.0beta8
    ```

**To Reproduce**

1. `jira ...` (e.g. `jira serverinfo --debug`)
2. Get 302
3. Curl equivalent command (e.g. `curl --request GET -H "Authorization: Bearer $JIRA_API_TOKEN" --url 'https://ad.astra.com/do/secure/rest/api/2/search?jql=project%3D%<redacted>%22+ORDER+BY+created+DESC&startAt=0&maxResults=100')
4. Get 302
5. Curl with `-L` to follow forwarding requests (e.g. `curl  -L --request GET -H "Authorization: Bearer $JIRA_API_TOKEN" --url 'https://ad.astra.com/do/secure/rest/api/2/search?jql=project%3D%<redacted>%22+ORDER+BY+created+DESC&startAt=0&maxResults=100`)
6. Get requested data

**Expected behavior**
302's and 301's should be followed.

**Comment by ankitpokhrel** [comment]
Hi @timfallmk, could you please check if #530 fixes your issue. You can install it with the following command.

```sh
go install github.com/ankitpokhrel/jira-cli@fix-527
```

**Comment by timfallmk** [comment]
I got it working temporarily by checking out the branch and building. Here's the output I get:
```shell
./jira board list
Error: invalid character '<' looking for beginning of value
```
Happens for all commands.

**Comment by djfjeff** [comment]
I have the same ```Error: invalid character '<' looking for beginning of value``` on my end with the fix-527 build

**Comment by ankitpokhrel** [comment]
@djfjeff Could you please use the `--debug` flag and see if the tool is hitting the correct URL and what response you are getting?

**Comment by djfjeff** [comment]
with --debug, I see that it hit the right URL and here is the start of the response section :

```
RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 200 OK
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/html;charset=UTF-8
```

**Comment by ankitpokhrel** [comment]
> Content-Type: text/html;charset=UTF-8

@djfjeff Even though the status code is `200`, the content seem to be a HTML page (Perhaps some error page). This explains the error `invalid character '<'`. Could you please check what error you are getting there? I believe this is something related to your setup or config.

**Comment by djfjeff** [comment]
You are right, it was a config issue. I don't know why but my config had Cloud instead of Local (don't know why and how it got there). Switching back to Local fixed everything on my end. Thanks!

**Comment by timfallmk** [comment]
Sorry, I wasn't able to test until today. I also get a 200, with the following payload:
```shell
RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 200
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Type: text/html;charset=UTF-8
Date: Mon, 09 Jan 2023 21:00:11 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: JSESSIONID=5A8A8D7B92B4F4354681C8F920435BE2; Path=/do; HttpOnly
Set-Cookie: atlassian.xsrf.token=BMDD-EPAM-PAYL-1ALU_7c6751c1df2056f03c3ff3c49660b92dc70542e9_lin; Path=/do
Strict-Transport-Security: max-age=31536000
Vary: User-Agent
X-Arequestid: 1260x283267x1
X-Asessionid: c88o65
X-Ausername: tfall
X-Content-Type-Options: nosniff
X-Seraph-Loginreason: OK
X-Xss-Protection: 1; mode=block
```

**Comment by ankitpokhrel** [comment]
@timfallmk I think this is same case as as above. I see `Content-Type: text/html;charset=UTF-8` in your response. So, even though the status code is `200`, the content seem to be a HTML page (some error page). Please check the error you are getting there. This is most probably something related to your setup or config.

**Comment by timfallmk** [comment]
@ankitpokhrel What would be the best way to debug this? I've checked over my config and the request URL and I can't see anything obviously wrong. Is there a way to get the payload or a raw `curl` request I can construct?
Running a raw request against that URL (without the authorization headers gives me a 302 which forwards to our SSO provider)

**Comment by timfallmk** [comment]
Actually I think I managed to replicate it: The response body I get _appears_ to be the login page. Here's a snippet:
```html
<form action="/do/login.jsp"
      class="aui"

      id="login-form"


      method="post">
    <div class="form-body">























    <div class="aui-group jira-login-method">
        <div class="aui-item jira-login-item">






<div class="field-group">

                    <label accesskey="u" for="login-form-username"><u>U</u>sername</label>
                    <input class="text medium-field" id="login-form-username" name="os_username" type="text" value="" />


</div>






<div class="field-group">

                    <label accesskey="p" for="login-form-password" id="passwordlabel"><u>P</u>assword</label>
                    <input id="login-form-password" class="text medium-field" name="os_password" type="password" />


</div>
```

**Comment by timfallmk** [comment]
Confirmed. Looking at the redirect chain, it looks something like this:
```shell
https://<host>/secure/rest/api/2/serverInfo
https://<host>/login.jsp?os_destination=https<host>%2Fsecure%2Frest%2Fapi%2F2%2FserverInfo
```

**Comment by glucas** [comment]
I hit the 302 redirect issue and the proposed patch works for me.

**Comment by timfallmk** [comment]
For some reason clearing my server config and re-initializing solved my problem here. Thanks for the work!
