### ISSUE TITLE
Feature request: Creating a git branch from a jira issue

### ISSUE THREAD

**Issue by Mellbourn** [ankitpokhrel/jira-cli#533]
I love how the Jira CLI enables me to quickly create an issue. Invariably, after I've created an issue I want to create a git branch based on the issue and check that out.

It would be very smooth if that functionality was built into jira-cli, perhaps as a flag to `jira issue create`.

I do know that I can use the `--web` flag and in that in the web GUI it is easy to generate a git command to create the git branch. But if I wanted to use the web GUI, I wouldn't be using jira-cli ;)

I did find the https://github.com/shaharkazaz/jiranch tool, but it seems quite buggy.

**Comment by ankitpokhrel** [comment]
Hi @Mellbourn, I think this would be a bit out of scope of this project. We should be able to use a simple shell script to do this and I could add in the documentation if someone comes up with a good one. One very basic example is shown below.

```sh
$ jira issue list -q"KEY=ISS-1" --plain --columns KEY,SUMMARY --no-headers | sed 's/ /_/g; s/\t/_/g'
```

Assuming the issue title is "This is a test", the above script would give you `ISS-1_This_is_a_test` that you can forward to git cli to create a branch.

**Comment by benoittgt** [comment]
I would love to be able to copy past a string that looks like a branch name at least :) 

Most the time my flow is. Look at issue, view one, create branch, work, modify status.
