### ISSUE TITLE
Missing Fish Completions

### ISSUE THREAD

**Issue by philipbjorge** [ankitpokhrel/jira-cli#552]
**Describe the bug**
There are no fish completions.

**Please provide following details**
1. JiraCLI Version:
    ```
(Version="1.3.0", GitCommit="ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed", CommitDate="2023-01-02T09:59:32+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="darwin/arm64")
    ```

**To Reproduce**

1. `jira completion fish`

**Expected behavior**
I expect some sort of output that can then be used to enable completions.

**Actual behavior**
Nothing

**Additional context**

I think there's a missing case statement here as cobra does look to support fish.
https://github.com/ankitpokhrel/jira-cli/blob/main/internal/cmd/completion/completion.go#L65

**Comment by ankitpokhrel** [comment]
This should be fixed with #553. Thank you for reporting @philipbjorge!
