### ISSUE TITLE
Give a flag to leave the epic link/epic name blank during init

### ISSUE THREAD

**Issue by Goldielocks** [ankitpokhrel/jira-cli#555]
**Is your feature request related to a problem? Please describe.**
Older workflows that don't use the Epic Link/Epic Name in the field throw an error since 1.2.0 since the generated config pulls a field that isn't available in the creation page. If these fields are populated in the config, creating an issue assumes they are usable.

**Describe the solution you'd like**
Ideally during `jira init` but optionally during `jira issue create` there should be a flag that sets these values to "" in the config or for that particular creation request respectively.

**Describe alternatives you've considered**
Updating the Jira workflow isn't likely to happen, and this adds an additional step to setup for users.

**Comment by ankitpokhrel** [comment]
> Older workflows that don't use the Epic Link/Epic Name in the field throw an error since 1.2.0 

Hi @Goldielocks, could you please elaborate a bit on this. A sample of command you used, error you get along with Jira server info would be helpful.

**Comment by stevemsmith** [comment]
I can help here - I believe my customfield_10006 (Epic Link) is applied and locked by a plugin called "Portfolio for JIRA"

When jira init is run the following is generated:
`board: ""
epic:
    name: customfield_10005
    link: customfield_10006
installation: Cloud
issue:
    fields:
        custom:
.....
 `

When I try and run a "jira issue create" I get:

`Error:
  - customfield_10006: Field 'customfield_10006' cannot be set. It is not on the appropriate screen, or unknown.

jira: Received unexpected response '400 Bad Request'.`

This field doesn't appear to be required and so passing a blank value is ok, but not sure that jira-cli knows how to pass an "Epic Link"?

I believe the workaround @Goldielocks was describing is what I ended up doing.  If I go into my .config.yml and change "customfield_10006" to "" everything works just fine.

So I think the real ask is - Is it possible for jira-cli to pass an "Epic Link" when creating issues.

**Comment by ankitpokhrel** [comment]
Hi @Goldielocks, @stevemsmith I couldn't reproduce the issue but it looks like the problem is that epic link field is being passed even when it is not actually needed. Could you please check if #607 fixes this issue?

You can install the fix using one of the following methods:
```sh
# using golang
go install github.com/ankitpokhrel/jira-cli/cmd/jira@issue-555

# with docker
docker run -it --rm ghcr.io/ankitpokhrel/jira-cli:issue-555
```
