### ISSUE TITLE
m does not allow transitioning of issue

### ISSUE THREAD

**Issue by KerberosKomondor** [ankitpokhrel/jira-cli#557]
**Describe the bug**
If I'm reading the documentation correctly, I should be able to press "m" on an issue while browsing through the results of jira issue list to transition an issue but pressing "m" does nothing.

**Please provide following details**
1. JiraCLI Version:
   
(Version="v1.3.0", GitCommit="", CommitDate="", GoVersion="go1.19.5", Compiler="gc", Platform="linux/amd64")

2. Are you using Jira cloud or on-premise jira server?

    SERVER INFO
-----------

Version:         1001.0.0-SNAPSHOT
Build Number:    100214
Deployment Type: Cloud
Default Locale:  en_US

3. What operating system are you using? Also mention version.

    Linux 6.1.6-arch1-1 1 SMP PREEMPT_DYNAMIC Sat, 14 Jan 2023 13:09:35 +0000 x86_64 GNU/Linux

4. What terminal are you using? Also mention version.

wezterm 20221119-145034-49b9839f

**To Reproduce**

1. jira issue list -a$(jira me)
2. scroll up and down to highlight an issue
3. press "m"
4. nothing happens

**Expected behavior**
I'm not sure exactly what it's supposed to do but I'm guessing it would ask for the next status like jira issue move.

**Screenshots**

**Additional context**
I have tried inside out outside of tmux just in case.

Thanks!

**Comment by ankitpokhrel** [comment]
Hi @KerberosKomondor, this feature is not released yet. If you wish to use the feature you can either [compile the binary manually](https://github.com/ankitpokhrel/jira-cli#development) or use one of the following means to install dev build.

```sh
# Docker
docker run -it --rm ghcr.io/ankitpokhrel/jira-cli:main

# Golang
go install github.com/ankitpokhrel/jira-cli/cmd/jira@main

# Homebrew
$ brew install jira-cli --HEAD
```

**Comment by KerberosKomondor** [comment]
Thanks!
