### ISSUE TITLE
worklog `--comment` flag do not work together with prompt

### ISSUE THREAD

**Issue by sarathsprakash** [ankitpokhrel/jira-cli#561]
**Describe the bug**
Worklog `--comment` flag with prompt mode will not get the the comment updated. To reproduce

```
jira issue worklog add TEST --comment "Test"
? Time spent 15m
? What's next? Submit

Worklog added to issue "TEST"
```

However when checking the entry in jira the `comment/description is missing` . This is fine if with `--no-input` flags supplied

**Please provide following details**
1. JiraCLI Version:

`(Version="v1.3.0", GitCommit="ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed", CommitDate="2023-01-02T09:59:32+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="linux/amd64")`

2. Are you using Jira cloud or on-premise jira server?
```
on-premise
SERVER INFO
-----------

Version:         8.13.4
Build Number:    813004
Deployment Type: Server
Default Locale
```

4. What operating system are you using? Also mention version.
`Host centos7.9 - docker container`

5. What terminal are you using? Also mention version.
`bash`

**To Reproduce**

`jira issue worklog add <ISSUE> --comment "Test comment"`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ankitpokhrel** [comment]
Hi @sarathsprakash, this should be fixed with #562. Thank you for reporting!
