### ISSUE TITLE
when ticket creation/editing fails, user entered data should be preserved / displayed

### ISSUE THREAD

**Issue by danpritts** [ankitpokhrel/jira-cli#564]
**Describe the bug**
When ticket creation fails, jira-cli provides a reasonable error message.  However, issue text that I entered is lost.

**Please provide following details**

1. JiraCLI Version:
```
(Version="v1.3.0", GitCommit="", CommitDate="", GoVersion="go1.19.5", Compiler="gc", Platform="darwin/amd64")
```

2. Are you using Jira cloud or on-premise jira server?
```
Version:         1001.0.0-SNAPSHOT
Build Number:    100214
Deployment Type: Cloud
Default Locale:  en_US
```

3. What operating system are you using? Also mention version.
```
macos 13.2 (22D49)
```

4. What terminal are you using? Also mention version.
```
Iterm 2 Build 3.4.19
```

**To Reproduce**

1.  break your config file somehow so that issue creation will fail.  In my case, I was attempting to add custom field info.  (This is not a question/report about how to make my configuration work, but rather about behavior upon failure.)
2. start `jira issue create` to create an issue.  
3. Edit the text in vim.   
4. When creation fails, you'll get an error message, but the text you entered will be gone in the ether

**Expected behavior**
The text I entered in the description should be printed to the terminal so I can copy & paste for reuse.  

Ideally, anything else i entered should be printed out too, but i can imagine that's a lot harder - and the description seems likely to be the one where people would've put effort.  

The summary was still there from where i entered it - I can imagine that might change in a future version, though, so might be nice to print that out too.

I haven't tested but I bet that `jira edit` behaves similarly.  I am a new user so perhaps there are other commands that would have similar issues that I am not aware of.  

If it is useful for me to test `jira edit` or other commands I am happy to.  

**Screenshots**
<img width="1058" alt="screenshot-missingdescription" src="https://user-images.githubusercontent.com/1068849/215225800-99183941-b41a-4d41-b841-c9035e90a71a.png">

**Comment by ankitpokhrel** [comment]
This looks related to #490

**Comment by danpritts** [comment]
agreed, I'll close this as duplicate.
