### ISSUE TITLE
`PAGER` documentation

### ISSUE THREAD

**Issue by prateek** [ankitpokhrel/jira-cli#565]
First off, this project's incredibly cool - so thank you for it.

I have `LESS=-FXRj.5` set in my shellrc file [1] to change how `less` behaves. The `-F` in particular made it so that I was not able to see "short issues" from the TUI. I eventually just changed my invocation of jira to be wrapped behind a function for other reasons (auth), as a result I just stuck in `LESS="-+j.5R" command jira "$@"` in my rc to get everything back to normal. 

Two specific asks:
- The docs/comments don't explicitly mention the TUI uses `less` as the PAGER. We should change that. I assumed the application had it's own because it had it's own TUI. 
- Allow users to explicitly set what options are used for the pager. E.g. JIRA_PAGER_OPTIONS or some such. 

Happy to put up a diff if we agree on a path forward. 

[1]: https://github.com/prateek/dotfiles/blob/52b0d59f5200075cf56a1570a189efefcfaf9ab6/zprofile#L13-L18

**Comment by ankitpokhrel** [comment]
Hi @prateek, #570 adds a new env `JIRA_PAGER` that should fix this issue. Let me know if I missed anything. And docs are updated, thank you for reporting!

Example:
```
$ JIRA_PAGER="less -R" jira issue view ISS-1
$ JIRA_PAGER=bat jira issue view ISS-1
```

**Comment by prateek** [comment]
@ankitpokhrel you're incredible, thank you 🙏
