### ISSUE TITLE
`jira init --config PATH` overwrites `~/.config/.jira/.config.yml` without warning

### ISSUE THREAD

**Issue by aes256Slater** [ankitpokhrel/jira-cli#576]
**Describe the bug**

When doing
```bash
jira init 
```

You get a very clear prompt
```
? Config already exist. Do you want to overwrite? (y/N)
```

But when doing

```
jira init --config PATH
```

You get no prompt and at the end of a successful setup, a config will overwrite the default location (`~/.config/.jira/.config.yml`) where one might expect `PATH` to be written with config

**Please provide following details**
1. JiraCLI Version:
```bash
$ jira version
(Version="v1.3.0", GitCommit="", CommitDate="", GoVersion="go1.19", Compiler="gc", Platform="linux/amd64")
```
2. Are you using Jira cloud or on-premise jira server?
 ```
SERVER INFO
-----------

Version:         9.4.2
Build Number:    940002
Deployment Type: Server
Default Locale:
 ```
3. What operating system are you using? Also mention version.
    ```
    Linux Mint 20
    ```
4. What terminal are you using? Also mention version.
    ```
    GNOME Terminal
    ```

**To Reproduce**

1. `jira init -c anything`

**Expected behavior**

I expect the config to be written to the given path. I expect a warning if a config exists in that location

**Screenshots**

**Additional context**

**Comment by ankitpokhrel** [comment]
This is fixed with #582. Thanks for reporting!
