### ISSUE TITLE
Creating a Task in new project generates the error "Field 'customfield_10014' cannot be set"

### ISSUE THREAD

**Issue by d1rewolf** [ankitpokhrel/jira-cli#586]
**Describe the bug**
I've created a new project for testing jira-cli, and have only allocated a "Task" issue type to it. However, I am unable to successfully create a task.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.3.0", GitCommit="ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed", CommitDate="2023-01-02T09:59:32+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="darwin/arm64")

    ```
2. Are you using Jira cloud or on-premise jira server?
```
  Version:         1001.0.0-SNAPSHOT
  Build Number:    100217
  Deployment Type: Cloud
  Default Locale:  en_US
```
4. What operating system are you using? Also mention version.
    ```
    macOS Ventura 13.2.1
    ```
5. What terminal are you using? Also mention version.
    ```
    iTerm 2 Build 3.4.19
    ```

**To Reproduce**

1. jira issue create --debug -p<myprojectid> -tTask
2. Type in a Summary
3. Type in a Description
4. Hit Submit

**Expected behavior**
The Task should be created, but it's not.

**Screenshots**
```
    % jira issue create --debug  -pDTP -tTask
    Using config file: /Users/d1rewolf/.config/.jira/.config.yml
    ? Summary Test task
    ? Description <Received>
    ? What's next?  [Use arrows to move, type to filter]
    > Submit
      Add metadata
      Cancel
    ⠼ Creating an issue...
    
    REQUEST DETAILS
    ------------------------------------------------------------
    
    POST /rest/api/2/issue HTTP/1.1
    Host: myhost.atlassian.net
    Accept: application/json
    Authorization: Basic 
    </snip>
    Content-Type: application/json
    
    
    Error:
      - customfield_10014: Field 'customfield_10014' cannot be set. It is not on the appropriate screen, or unknown.
    
    jira: Received unexpected response '400 Bad Request'.
    Please check the parameters you supplied and try again.
```

**Additional context**

**Comment by d1rewolf** [comment]
Looking at my config, customfield_10014 seems to be the link to Epic:

  Read the doc or get help at https://github.com/ankitpokhrel/jira-cli
  
```
  board: ""
  epic:
    name: customfield_10011
    link: customfield_10014
  installation: Cloud
  issue:
```

However, attempting to use the parent flag has no effect.

**Comment by d1rewolf** [comment]
For your reference, this is a "next-gen" project.

**Comment by d1rewolf** [comment]
Following the comments in #555, I was able to resolve it. Setting the link to "" in .config.yml allowed me to create the issue:

```
  board: ""
  epic: 
    name: customfield_10011
    link: ""
  installation: Cloud
```

After saving, I am able to create an issue...

```
? Summary asdlkfjasdf
? Description <Received>
? What's next? Submit
⠇ Creating an issue...

REQUEST DETAILS
------------------------------------------------------------

POST /rest/api/2/issue HTTP/1.1
Host: empireauto.atlassian.net
Accept: application/json
Authorization: Basic <snip/>
Content-Type: application/json


✓ Issue created
```

**Comment by ankitpokhrel** [comment]
Hi @d1rewolf, could you please check if https://github.com/ankitpokhrel/jira-cli/pull/607 fixes this issue?

You can install the fix using one of the following methods:
```sh
# using golang
go install github.com/ankitpokhrel/jira-cli/cmd/jira@issue-555

# with docker
docker run -it --rm ghcr.io/ankitpokhrel/jira-cli:issue-555
```
