### ISSUE TITLE
Add support for Affected Versions (or just versions)

### ISSUE THREAD

**Issue by Roobxyz** [ankitpokhrel/jira-cli#587]
> Please consider [opening a discussion](https://github.com/ankitpokhrel/jira-cli/discussions/categories/ideas) in `ideas` category if applicable. Your feature will be prioritized on based on the number of votes.  

**Is your feature request related to a problem? Please describe.**
Affected Versions is a native JIRA field - so would be good to add support for it (not sure if we can reach it with custom fields)
https://www.atlassian.com/agile/tutorials/versions#:~:text=Affects%20version%20is%20the%20version,feature%20or%20bugfix%20to%20customers.

**Describe the solution you'd like**
To be able to supply `--affected-versions` during a `jira issue create`

**Describe alternatives you've considered**
Looked at custom fields but couldn't understand it

**Additional context**
A snippet from a request made directly to the API below shows `versions` is a first class field and is distinct to `fixVersions`
```
    "fixVersions": [],
    ...
    "timeestimate": null,
    "customfield_10218": null,
    "customfield_10219": null,
    "versions": [
      {
       "self":...
       "id":....
       "description":...
       "archived":....
       "released":.....
     }]
```

**Comment by damianoneill** [comment]
@ankitpokhrel @Roobxyz its not called out explictly here but assume the same request for --fix-versions support for the native jira field Fix Versions as these are likely to be used at the same time in several scenarios.

**Comment by damianoneill** [comment]
Ignore the comment above, just noticed the fix-version already exists as a command line option.

**Comment by ankitpokhrel** [comment]
Done with #642

**Comment by Roobxyz** [comment]
❤️
