### ISSUE TITLE
Connectivity issue: Error: EOF

### ISSUE THREAD

**Issue by MattPD** [ankitpokhrel/jira-cli#597]
**Describe the bug**

Since today I can no longer use JiraCLI with my Jira instance and I'm getting `Error: EOF` instead.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.3.0", GitCommit="ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed", CommitDate="2023-01-02T09:59:32+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server?
    On-premises "Data Center" edition.
    AboutPage.jspa says "Jira v9.4.1"

```
$ jira serverinfo
Error: EOF

$ jira serverinfo --debug
Using config file: /home/users/matt/.config/.jira/.config.yml
⠼ Fetching server info...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/serverInfo HTTP/1.1
Host: [hostname elided]:8443
Authorization: Basic [elided]]==

Error: EOF
```

Edit: I've managed to connect via another host which outputs:
```
SERVER INFO
-----------

Version:         9.4.1
Build Number:    940001
Deployment Type: Server
Default Locale:
```

Now, is there a way to diagnose where the issue lies?
(Perhaps it's a problem specific to the host I'm attempting to connect from?)

3. What operating system are you using? Also mention version.
```
SUSE Linux Enterprise Server 15 SP3
Linux 5.3.18-59.37-default x86_64
```

**To Reproduce**

1. jira serverinfo
2. jira issue list
3. jira issue list --debug

Any of the above commands displays an error just like in the provided `jira serverinfo [--debug]` output.

**Comment by ankitpokhrel** [comment]
Hi @MattPD,

Could you check what response you get with the direct cURL request?

```sh
$ curl -vvv --request GET \
  --url 'https://<host>/rest/api/2/serverInfo' \
  --user "<user>:$JIRA_API_TOKEN"
```

**Comment by MattPD** [comment]
Thanks! It's started to work now (all hosts can connect via `curl`, too), so I'm going to close and hope this won't reappear :-)
