### ISSUE TITLE
Unable to create sub-tasks

### ISSUE THREAD

**Issue by WillPlatnick-S1** [ankitpokhrel/jira-cli#605]
**Describe the bug**
Unable to create sub-tasks

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.3.0", GitCommit="ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed", CommitDate="2023-01-02T09:59:32+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="darwin/arm64")
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    SERVER INFO
-----------

Version:         1001.0.0-SNAPSHOT
Build Number:    100221
Deployment Type: Cloud
Default Locale:  en_US
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS Ventura 13.3.1
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm 2 Build 3.4.19
    ```

**To Reproduce**

I had a related issue when I was trying to create a subtask for an issue that had an epic created.

In my config, I had:
```
epic:
  name: customfield_10010
  link: customfield_10008
```

When I tried to run: 
jira issue create -tSub-task -pPROJECT -PTICKET-NO -s"Test" --no-input -a`jira me` 

Error:
  - customfield_10008: Field 'customfield_10008' cannot be set. It is not on the appropriate screen, or unknown.

For me, to create the subtasks properly, I actually had to set this:
```
epic:
    name: customfield_10010
    link: ""
```
And it created successfully

**Expected behavior**
Sub-task creates successfully

**Screenshots**

**Additional context**

**Comment by ankitpokhrel** [comment]
Looks related to #555

**Comment by ankitpokhrel** [comment]
HI @WillPlatnick-S1, could you please check if https://github.com/ankitpokhrel/jira-cli/pull/607 fixes this issue?

You can install the fix using one of the following methods:
```sh
# using golang
go install github.com/ankitpokhrel/jira-cli/cmd/jira@issue-555

# with docker
docker run -it --rm ghcr.io/ankitpokhrel/jira-cli:issue-555
```
