### ISSUE TITLE
`404 Not Found` on selecting the default board

### ISSUE THREAD

**Issue by rexagod** [ankitpokhrel/jira-cli#626]
**Describe the bug**

Hello! 👋🏼 I'm trying to set this up for an internal board that's under a project, but this fails with a 404.

```
┌[rexagod@nebuchadnezzar] [/dev/pts/0] [1]
└[~]> jira init
? Installation type: Cloud
? Link to Jira server: https://issues.redhat.com
? Login email: <email>
? Default project: <project>
? Default board: <board>

✗ Received unexpected response '404 Not Found' from jira. Please try again.
```

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="main", GitCommit="eb842e18014303a575fde8e19508b3c7c13982c5", CommitDate="2023-05-09T07:09:45+00:00", GoVersion="go1.20.4", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    ✗ Missing configuration file.
	Run 'jira init' to configure the tool.
    ```
3. What operating system are you using? Also mention version.
    ```
    NAME="Fedora Linux"
	VERSION="38 (Workstation Edition)"
	ID=fedora
	VERSION_ID=38
    ```
4. What terminal are you using? Also mention version.
    ```
    kitty 0.28.1
    ```

**To Reproduce**

1. I encountered some errors initially, so I followed https://github.com/ankitpokhrel/jira-cli/issues/477#issuecomment-1258364716 to fix them.
2. On selecting a board, it still seems to fail (with a different error, 404).

**Expected behavior**
It successfully fetches the board details and creates the config.

**Comment by ankitpokhrel** [comment]
Hi @rexagod,

To make sure I understand the problem correctly, are you are getting 404 after selecting the board that is listed in `Default board` dropdown? 

Few asks to help with the debugging:
- Could you please check which API fails using the `--debug` flag?
- There is a `--board` flag available in the `init` cmd that can be used to skip board selection step. That should help you with config generation. Does this temporarily solve your problem?

**Comment by rexagod** [comment]
@ankitpokhrel Thank you for looking into this! Please find the answers to your questions below, and feel free to let me know if I can help with anything else from my side! :)

> To make sure I understand the problem correctly, are you are getting 404 after selecting the board that is listed in Default board dropdown?

Correct.

> Could you please check which API fails using the --debug flag?

```
┌[rexagod@nebuchadnezzar] [/dev/pts/0] 
└[~]> jira init --debug
? Installation type: Cloud
? Link to Jira server: https://issues.redhat.com
? Login email: <email>
⠹ Verifying login details...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/myself HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

⠇ Fetching projects...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/project?expand=lead HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

? Default project: <project>
⠇ Fetching boards for project <project>...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/agile/1.0/board?projectKeyOrId=<project> HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

? Default board: <board>
⠸ Configuring metadata. Please wait...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/issue/createmeta?projectKeys=<project>&expand=projects.issuetypes.fields HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]


✗ Received unexpected response '404 Not Found' from jira. Please try again.
```

> There is a --board flag available in the init cmd that can be used to skip board selection step. That should help you with config generation. Does this temporarily solve your problem?

Doesn't seem like it. :/

```
┌[rexagod@nebuchadnezzar] [/dev/pts/0] [1]
└[~]> jira init --board "<board>" --debug
? Installation type: Cloud
X Sorry, your reply was invalid: not a valid URL
? Link to Jira server: https://issues.redhat.com
? Login email: <email>
⠏ Verifying login details...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/myself HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

⠦ Fetching projects...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/project?expand=lead HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

? Default project: <project>
⠏ Fetching boards for project '<project>'...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/agile/1.0/board?projectKeyOrId=<project> HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

⠼ Configuring metadata. Please wait...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/issue/createmeta?projectKeys=<project>&expand=projects.issuetypes.fields HTTP/1.1
Host: issues.redhat.com
Authorization: Bearer [redacted]

✗ Received unexpected response '404 Not Found' from jira. Please try again.
```

**Comment by muehan** [comment]
I have the same problem, I guess the problem is that the new metadata endpoint ist not available in cloud.
https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html
https://community.atlassian.com/t5/Jira-questions/New-createmeta-REST-endpoint-solution-of-Jira-throws-404/qaq-p/1761393

**Comment by muehan** [comment]
same problem.
```
GET /rest/api/2/issue/createmeta?projectKeys=WEB&expand=projects.issuetypes.fields HTTP/1.1

RESPONSE DETAILS
------------------------------------------------------------

HTTP/1.1 404
```

jira version
`(Version="1.2.0", GitCommit="9d8a0afd75b68aa519367f93c240429117cc4090", CommitDate="2022-12-16T10:53:08+00:00", GoVersion="go1.18.3", Compiler="gc", Platform="windows/amd64")`

**Comment by ankitpokhrel** [comment]
Hi @muehan, thank you for checking. Could you please provide the output of `jira serverinfo` command, I will try to reproduce the issue.

**Comment by muehan** [comment]
Because if the error I can not run `jira init`

So the output is not helpful at all.
```
$ jira serverinfo
✗ Missing configuration file.
Run 'jira init' to configure the tool.
```

**Comment by joshangehr** [comment]
Just wanted to note that I am experiencing the same issues described above on a new machine on both `1.2` and `1.4`.

**Comment by ankitpokhrel** [comment]
Hi @muehan @joshangehr, since `serverinfo` command won't work without the config. Could you please use the following curl command to get the server info. I will try to replicate the issue.

```sh
$ curl -vvv --request GET \
  --url 'https://<server>/rest/api/2/serverInfo' \
  --user "<user>:<password>"

# If you are using bearer token
$ curl -vvv --request GET \
  -H "Authorization: Bearer <JIRA_API_TOKEN>" \
  --url 'https://<server>/rest/api/2/serverInfo'
```

**Comment by jonathf** [comment]
Hello, I am experiencing the exact same issue.

Here is my [serverinfo output](https://github.com/ankitpokhrel/jira-cli/files/11800642/serverinfo.txt).

**Comment by joshangehr** [comment]
@ankitpokhrel With your above feedback, I was able to resolve my issue. I had selected `Local` as I misinterpreted the meaning in the docs. After selecting `Cloud`, everything is working wonderfully.

**Comment by jonathf** [comment]
```
$ jira init --debug
? Installation type: Cloud
? Link to Jira server: https://jira.ruter.no
? Login email: [***]@ruter.no
⠹ Verifying login details...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/myself HTTP/1.1
Host: jira.ruter.no
Authorization: Bearer [***]

⠹ Fetching projects...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/project?expand=lead HTTP/1.1
Host: jira.ruter.no
Authorization: Bearer [***]

? Default project: TDS
⠹ Fetching boards for project 'TDS'...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/agile/1.0/board?projectKeyOrId=TDS HTTP/1.1
Host: jira.ruter.no
Authorization: Bearer [***]

? Default board: ML Team
⠹ Configuring metadata. Please wait...

REQUEST DETAILS
------------------------------------------------------------

GET /rest/api/2/issue/createmeta?projectKeys=TDS&expand=projects.issuetypes.fields HTTP/1.1
Host: jira.ruter.no
Authorization: Bearer [***]


✗ Received unexpected response '404 ' from jira. Please try again.
```
Seems to me the common denomenator between the OP and me is the fact that SSO is enabled, and to log on we have to use both `JIRA_AUTH_TYPE="bearer"` and `JIRA_API_TOKEN`.

**Comment by rexagod** [comment]
> I just noticed that you've selected Installation type as Cloud, [issues.redhat.com](https://issues.redhat.com/) is a Local installation so please select Local as an installation type during jira init. That should solve your issue.

@ankitpokhrel That worked, THANK YOU! ❤️

**Comment by jonathf** [comment]
Facinating, I missed that as well. All three of us assumed that the server should be cloud. It now works here as well.

Thank you for the help everyone.
 
I guess we can close the issue now.

**Comment by rexagod** [comment]
@ankitpokhrel Thanks again for the timely responses and all the work you put into this! 🚀

**Comment by beauso** [comment]
I just wanted to point out to any future readers: for me, it was important to choose `Local` in `jira init` _AND_ downgrade to `1.2.0`. I had read this thread and tried Local on `1.4.0` before downgrading, assuming that is what solved it for everyone.

(Jira server `9.4.x`).

**Comment by junousi** [comment]
> I just wanted to point out to any future readers: for me, it was important to choose `Local` in `jira init` _AND_ downgrade to `1.2.0`. I had read this thread and tried Local on `1.4.0` before downgrading, assuming that is what solved it for everyone.

Confirmed, also had to stick to `1.2.0` here to make a `Local` init work. I'm not 100% sure if this is the root cause, but current `main`/`64f1f0c1` seems to force a selection between `basic`/`mtls` even if `JIRA_AUTH_TYPE=bearer` is set, and thereafter refuses to use bearer.
