### ISSUE TITLE
Add a way to open the default browser while going through the issue list

### ISSUE THREAD

**Issue by remyleone** [ankitpokhrel/jira-cli#628]
**Is your feature request related to a problem? Please describe.**

I would like to open a browser for a given issue to see it in a web view (attached files)

**Describe the solution you'd like**

I would like to have a keyboard shortcut when I'm in the TUI that will open the browser for a given URL. The URL is already available using the "c" shortcut but I would like to have an open browser directly.

**Describe alternatives you've considered**

I could copy the URL, open the browser, pasting the URL directly in and hit enter. It seems to be extra long.

**Additional context**

I think this package could be useful: https://github.com/skratchdot/open-golang

**Comment by ankitpokhrel** [comment]
Hi @remyleone, does pressing `Enter` doesn't work for you?

**Comment by remyleone** [comment]
Ah sorry, I thought it didn't work because the focus didn't change to the browser. Thanks a lot
