### ISSUE TITLE
Transitioning issue does not work with 'm' using latest 1.4.0 release

### ISSUE THREAD

**Issue by desilinguist** [ankitpokhrel/jira-cli#675]
**Describe the bug**
I am successfully able to list my sprints and the issues in each sprint but pressing 'm' does nothing. Pressing 'v' does work.

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="1.4.0", GitCommit="eb842e18014303a575fde8e19508b3c7c13982c5", CommitDate="2023-05-09T07:09:45+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="darwin/arm64")
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    SERVER INFO
    -----------

    Version:         9.5.1
    Build Number:    950001
    Deployment Type: Server
    Default Locale:.
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS Ventura 13.6
    ```
4. What terminal are you using? Also mention version.
    ```
    Kitty v0.30.1
    ```

**To Reproduce**

1. Run `jira sprint list`
2. Select a sprint and then an issue.
3. Press 'm' and nothing happens. 

**Expected behavior**
It should allow me to transition the issue as expected.

**Comment by desilinguist** [comment]
Interesting, transitioning does work when I do `jira issue list -a$(lira me)`! Is it not supposed to work in sprint view?

**Comment by ankitpokhrel** [comment]
Hi @desilinguist, transitioning with 'm' is not available in the explorer view. I will consider adding it. 

This should work fine on the list view.
```
jira sprint list <sprint_id>
```

**Comment by desilinguist** [comment]
Thank you!
