### ISSUE TITLE
How can I get jira status list?

### ISSUE THREAD

**Issue by Wangggym** [ankitpokhrel/jira-cli#676]
> Please consider [opening a discussion](https://github.com/ankitpokhrel/jira-cli/discussions/categories/ideas) in `ideas` category if applicable. Your feature will be prioritized on based on the number of votes.  

**Is your feature request related to a problem? Please describe.**

In my project, I use github-cli and jira-cli to complete the quick workflow. See https://github.com/Wangggym/quick-workflow
and I want to get the Jira status list in different project.

**Describe the solution you'd like**

like is better:
```shell
jira project status list xxx
```
and return:
```shell
['In progress','Done']
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Wangggym** [comment]
@ankitpokhrel

**Comment by ankitpokhrel** [comment]
Hi @Wangggym, this is not directly possible from the tool yet. You will have to make an API call to get the status list.
