### ISSUE TITLE
Shell completions zsh not completing

### ISSUE THREAD

**Issue by nanvenomous** [ankitpokhrel/jira-cli#686]
**Describe the bug**
I followed the instructions in `jira completion --help` for zsh, but on `<tab>` I get the default directory completion

**Please provide following details**
1. JiraCLI Version:
    ```
    (Version="v1.4.0", GitCommit="", CommitDate="", GoVersion="go1.21.4", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? `Not yet set up (N/A)`
3. What operating system are you using? Also mention version.
    ```
    Arch Linux x86_64,  Kernel: 6.6.1-arch1-1
    ```
4. What terminal are you using? Also mention version.
    ```
     git@github.com:siduck/st.git commit: 5c4df963070573db7cee2eafb320d84e477c3507
    ```

**To Reproduce**

1. add `autoload -U compinit; compinit` to `~/.zshrc`
2.
```bash
jira completion zsh > _jira
mv ./_jira $fpath[1]
```
3. Start a new shell
4. run
```bash
jira <tab>
```

**Expected behavior**
- I would expect to see the array of top level commands from `jira` cli
- for example from my [dex](https://github.com/dexidp/dex) cli 
```bash
> dex <tab>
completion  -- Generate the autocompletion script for the specified shell
help        -- Help about any command
serve       -- Launch Dex
version     -- Print the version and exit
```

**Actual behavior**
- activating the completion on the newly installed jira cli defaults to file completion.
```bash
> jira <tab>
Android/       Images/        bin/           gin_logs/      projects/      run_llama.sh*
Documents/     Sync/          clauseout/     go/            public/        test.md
Downloads/     Videos/        devsquadron/   notes.md       readme.md
```

**Additional context**
- When I look at the contents of:
```bash
nvim $fpath[1]/_jira
```
it seems good.
- I have completion files in `$fpath[1]` for other binaries that are working
- I have also tried `source <(jira completion zsh)` which doesn't change anything.

**Comment by nanvenomous** [comment]
Once I authenticated and ran `jira init` now the completions work.

**Comment by nanvenomous** [comment]
Once I authenticated and ran `jira init` now the completions work.

**Comment by ankitpokhrel** [comment]
Hi @nanvenomous, since the completion config is auto generated via [spf13/cobra](https://github.com/spf13/cobra/blob/main/zsh_completions.go) lib, let's keep the behavior as is for now. Completions seem to work fine after configuring the tool.
