### ISSUE TITLE
`jira init` gets 403 on Account with Single Sign On

### ISSUE THREAD

**Issue by thomaslagies** [ankitpokhrel/jira-cli#746]
**Describe the bug**

We use JIRA Cloud and I want to run `jira init` like this:

![image](https://github.com/ankitpokhrel/jira-cli/assets/36266386/5f6d5df9-ec45-47cf-a7c9-85579c51735a)

**Please provide following details**
1. JiraCLI Version:
 
`Version="1.5.1", GitCommit="0e0f82d52ef5a775d2cc662fbe38d9732b9b5c59", CommitDate="2024-01-20T10:48:06+00:00", GoVersion="go1.21.5", Compiler="gc", Platform="darwin/arm64"`

2. Are you using Jira cloud or on-premise jira server?

Jira cloud: `jira serverinfo` is not working, even with exported JIRA_API_TOKEN

![image](https://github.com/ankitpokhrel/jira-cli/assets/36266386/45e8ef88-35ea-40e0-a46e-1e588a6c22f2)

3. What operating system are you using? Also mention version.
    ```
    macOS Sonoma 14.5
    ```
4. What terminal are you using? Also mention version.
    ```
    iTerm 2 Build 3.5.0 with tmux 3.4
    ```

**To Reproduce**

1. Install jira-cli via brew `https://github.com/ankitpokhrel/homebrew-jira-cli`
2. Run `jira init`

**Comment by thomaslagies** [comment]
My bad, I put the JIRA_API_TOKEN in a temp .env file and sourced it, which seems to not be working?

I did `export JIRA_API_TOKEN=xxxx` and `export JIRA_AUTH_TYPE=bearer`

and now I get:

![image](https://github.com/ankitpokhrel/jira-cli/assets/36266386/3b219223-1756-4bde-ba74-7e3a38979fd2)

**Comment by thomaslagies** [comment]
I got it working with setting `$JIRA_AUTH_TYPE` to an empty string

**Comment by oschrenk** [comment]
Oh man! Was also stumbling over this. 

I had `JIRA_AUTH_TYPE` set `bearer`. But it needs to be empty for `jira init` to work. Then it writes "auth_type" basic to the config although it is actually using PAT.
