### ISSUE TITLE
Add an exclude filter

### ISSUE THREAD

**Issue by jclsn** [ankitpokhrel/jira-cli#761]
**Is your feature request related to a problem? Please describe.**
If I want to list issues that are not "Done", I would have to filter for all other statuses.

**Describe the solution you'd like**
Be able to filter for all issues that are NOT in status "Done".

**Comment by ankitpokhrel** [comment]
Hi @jclsn, you can do the following:

```
$ jira issue list -s~Done
$ jira issue list -s~"To Do"
```

`~` acts as a not operator.

**Comment by jclsn** [comment]
Thanks! Maybe add this to the documentation or —help. Could not find it!
