### ISSUE TITLE
enable `--debug` flag for `init`?

### ISSUE THREAD

**Issue by jakdept** [ankitpokhrel/jira-cli#95]
So, I just spent some time trying to set this up and had some difficulty, apparently my API token was no good.

However, the `--debug` flag exists globally, but it specifically looks to not do a lot for the `init` subcommand. I would expect `jira init --debug` to give some useful output.

I got as far as:
`generator.go` line 170 changing that to:
```go
	c.jiraClient = api.Client(jira.Config{
		Server: server,
		Login:  login,
		Debug:  viper.GetBool("debug"),
	})
```

But then I did not see that debug output reflected in `client.go` line 130:
```go
func (c *Client) request(ctx context.Context, method, endpoint string, body []byte, headers Header) (*http.Response, error) {
	if c.debug {
		fmt.Printf("\nRequesting %s: %s\n", method, endpoint)
		fmt.Printf("With request body: %s\n", string(body))
		fmt.Printf("With request headers: %v\n", headers)
	}
```

And to be honest, before I went any further I added debug messages directly and saw I was getting a 401.

That aside, it would be nice to have `--debug` for `init` - including possibly `defer()` in that function to print out the response if debug is set?

Alternatively, maybe https://github.com/j0hnsmith/connspy/ if you don't want to roll your own?

**Comment by ankitpokhrel** [comment]
@jakdept `--debug` is a [PersistentFlag](https://github.com/spf13/cobra#persistent-flags) so you need to bind it first and that is missing [in root.go](https://github.com/ankitpokhrel/jira-cli/blob/master/internal/cmd/root/root.go#L92).

> including possibly defer() in that function to print out the response if debug is set?

I still need to make error message bit meaningful for end users but this addition would be great for now. I am open to PR :)
