### ISSUE TITLE
newline not parsing in markdown

### ISSUE THREAD

**Issue by gennaro-tedesco** [ankitpokhrel/jira-cli#99]
## Description
When writing the body of a ticket I have noticed that newlines do not parse as such. In particular

1. carriage return (just leaving a physical new line between paragraphs) does not insert a new line (the text is still attached in-line)
2. `\n` or `\r` characters are interpreted and inserted verbatim

## Terminal
I am using neovim on iterm2 - if that matters - to edit the body text of the tickets.

Has anybody met the same problem or do newlines just work fine (and for some reasons I am unable to have them work)?

**Comment by ankitpokhrel** [comment]
I can reproduce same issue with `vim`. Thank you for reporting!

**Comment by ankitpokhrel** [comment]
As a quick workaround you can use backslash for new lines `\`.

eg:
```
First line
\
Second line
```

**Comment by gennaro-tedesco** [comment]
Thank you for looking into it! The backslash `\` seems to be working fine for the moment.
